# yaml-language-server: $schema=./src/automated_security_helper/schemas/ASHConfig.json
project_name: automated-security-helper
build:
  build_mode: ONLINE
  custom_scanners: []
fail_on_findings: true
global_ignore_paths:
  - path: 'tests/test_data'
    reason: This is test data that is used during unit testing only and is not part of the core application.
  - path: .venv
    reason: This path contains .gitignore'd cache data used by dev/build tools.
  - path: .git
    reason: This path contains .gitignore'd cache data used by dev/build tools.
  - path: .ruff
    reason: This path contains .gitignore'd cache data used by dev/build tools.
  - path: .pytest_cache
    reason: This path contains .gitignore'd cache data used by dev/build tools.
  - path: .mypy_cache
    reason: This path contains .gitignore'd cache data used by dev/build tools.
output_formats:
  - sarif
  - junitxml
  - html
  - cyclonedx
  - asff
  - ocsf
  - text
severity_threshold: ALL
scanners:
  bandit:
    enabled: true
    options:
      confidence_level: all
      severity_level: all
      ignore_nosec: false
      excluded_paths: []
  cdk-nag:
    enabled: true
    options:
      nag_packs:
        AwsSolutionsChecks: true
        HIPAASecurityChecks: true
        NIST80053R4Checks: true
        NIST80053R5Checks: true
        PCIDSS321Checks: true
  cfn-nag:
    enabled: true
  checkov:
    enabled: true
    options:
      frameworks:
        - all
      additional_formats:
        - cyclonedx_json
      skip_path: []
  detect-secrets:
    enabled: true
  npm-audit:
    enabled: true
  grype:
    enabled: true
  semgrep:
    enabled: true
  syft:
    enabled: true
