# A deliberately small ASH image, for the end-to-end test only.
#
# Not a substitute for the real one. It carries the two scanners that are pure
# Python -- bandit and detect-secrets -- and none of the eight that need ruby, node,
# npm or a Go binary. That is enough to prove the contract, because what the e2e has
# to demonstrate is that a real `ashx scan` ran per shard, that its provenance was
# stamped, that the merge consumed every index and that a planted finding came back.
# A scanner that needs a toolchain would add minutes to the build and test nothing
# the operator is responsible for.
#
# The image is loaded into kind with `kind load docker-image`, so it is never pushed
# anywhere. ASH publishes no public image and neither does this.
#
# EVERY PACKAGE IS INSTALLED FROM A HASHED, VERSION-PINNED FILE (pip --require-hashes):
#
#   locks/ash-runtime.txt               ASH's dependencies, exported from the repository's
#                                       uv.lock by helpers.stage_ash_locks while staging
#                                       this context, so they are the versions every other
#                                       ASH test runs against
#   locks/scanner-requirements.txt      bandit with ASH's extras, beside ASH
#   locks/ash-build-requirements.txt    hatchling, to build the ASH wheel
#
# The ASH wheel is built in its own stage with --no-build-isolation, because pip's
# isolated build environment fetches the build backend from the index with no hash
# check. The two committed files are regenerated by ../../relock.sh.
#
# Pinned by digest (.github/scripts/assert-images-pinned.py enforces it): the multi-arch
# index python:3.12-slim resolved to on 2026-10-09 (Python 3.12.15). Both stages name the
# same digest.
FROM python:3.12-slim@sha256:a6e34c598f2467ed0e9a8d349809fcd8b5c603269512df273a0bb1784edc11b1 AS build

COPY locks/ash-build-requirements.txt /locks/
RUN pip install --no-cache-dir --require-hashes -r /locks/ash-build-requirements.txt
COPY ash-source /src
RUN pip wheel --no-cache-dir --no-deps --no-build-isolation --no-index --wheel-dir /wheels /src

FROM python:3.12-slim@sha256:a6e34c598f2467ed0e9a8d349809fcd8b5c603269512df273a0bb1784edc11b1

# A writable HOME that is not root's. Kubernetes' runAsUser overrides the image's
# USER but does NOT consult /etc/passwd for a home directory, so HOME has to come
# from the image environment or it defaults to "/" -- and a scanner that cannot
# write a cache directory comes back MISSING, which merges into a report that reads
# as a complete scan.
RUN useradd --uid 1000 --create-home --home-dir /home/ash --shell /bin/sh ash
ENV HOME=/home/ash \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Kubernetes never reads a Docker HEALTHCHECK, and this image runs `ashx scan` to
# completion in a Job rather than serving anything, so there is nothing to probe.
# NONE says so explicitly instead of leaving it to be inferred.
HEALTHCHECK NONE

COPY locks/ash-runtime.txt locks/scanner-requirements.txt /locks/
COPY --from=build /wheels /wheels

# bandit is installed with the sarif and toml extras ASH asks for, inside its version
# range, so ASH's pre-installed-tool check (utils/pre_installed_tool.py) finds the
# binary on PATH satisfies the requirement and runs it directly. Nothing is fetched at
# scan time: the uv tool environment this image used to warm with an unpinned
# `uv tool install bandit` is gone, and with it the one unhashed download the image made.
#
# The ASH wheel goes in with --no-deps --no-index, so it can add nothing the hashed
# files did not, and `pip check` proves those files are its whole dependency closure
# and bandit's.
RUN pip install --no-cache-dir --require-hashes \
        -r /locks/ash-runtime.txt -r /locks/scanner-requirements.txt \
    && test "$(find /wheels -name 'automated_security_helper-*.whl' | wc -l)" -eq 1 \
    && pip install --no-cache-dir --no-deps --no-index /wheels/automated_security_helper-*.whl \
    && pip check \
    && python -c "import automated_security_helper; print(automated_security_helper.__version__)" \
    && ashx --version \
    && bandit --version \
    && detect-secrets --version \
    && chown -R 1000:1000 /home/ash

USER 1000
WORKDIR /workspace
