"""Shared helpers for the end-to-end test.

A module rather than importing from ``conftest.py``: a conftest is a plugin, and
importing one by path gives two module objects with two copies of the constants the
moment anything changes the collection root.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from pathlib import Path

import yaml

from ash_operator import constants

# Both overridable so concurrent runs on one host -- or a CI runner and a developer
# -- never share a cluster or an image tag. The images are only ever loaded into
# kind (`kind load docker-image`); nothing in this harness pushes them anywhere.
CLUSTER_NAME = os.environ.get("ASH_OPERATOR_E2E_CLUSTER", "ash-operator-e2e")
IMAGE_TAG = os.environ.get("ASH_OPERATOR_E2E_IMAGE_TAG", "local")
NAMESPACE = "ash-system"
ASH_IMAGE = f"ash-e2e:{IMAGE_TAG}"
# An ASH whose ScanPhase does not stamp candidate_scanners, for the provenance
# negative control. See tests/e2e/Dockerfile.ash-nostamp.
ASH_IMAGE_NOSTAMP = f"ash-e2e-nostamp:{IMAGE_TAG}"
OPERATOR_IMAGE = f"ash-operator:{IMAGE_TAG}"
GROUP = constants.GROUP
TERMINAL = frozenset(constants.TERMINAL_PHASES)

E2E_DIR = Path(__file__).resolve().parent
OPERATOR_DIR = E2E_DIR.parents[1]
REPO_ROOT = OPERATOR_DIR.parents[1]


# Root-level files the ASH wheel build reads. "Dockerfile" is the one that is easy to
# miss: pyproject.toml force-includes automated_security_helper/assets/Dockerfile,
# which is gitignored and which hatch_build.py generates from the root Dockerfile
# during the build. Without the root file in the context, `pip install .` fails with
# "Forced include not found ... assets/Dockerfile".
ASH_SOURCE_FILES = (
    "pyproject.toml",
    "README.md",
    "LICENSE",
    "NOTICE",
    "hatch_build.py",
    "Dockerfile",
)
# What hatch_build.py writes into automated_security_helper/assets/, all gitignored.
# Never copied: a copy left in a developer's checkout by an earlier build would stand
# in for the one this build has to generate, which is how a context missing the root
# Dockerfile built locally and failed on every clean CI checkout.
ASH_GENERATED_ASSETS = frozenset(
    {"Dockerfile", "ASH_INSTALLED_REVISION", "tool_downloads.py", "exceptions.py"}
)


def stage_ash_source(dest: Path, repo_root: Path = REPO_ROOT) -> None:
    """Copy what an ASH wheel build needs from ``repo_root`` into ``dest``.

    Only that, rather than the whole checkout, which would drag in .git, other work
    in progress and any venv sitting in it. Every listed file is required: a context
    that silently lacks one builds an image from something other than the checkout.
    """
    dest.mkdir(parents=True, exist_ok=True)
    missing = [name for name in ASH_SOURCE_FILES if not (repo_root / name).is_file()]
    if missing:
        raise FileNotFoundError(f"the ASH build context needs {missing} from {repo_root}")
    for name in ASH_SOURCE_FILES:
        shutil.copy(repo_root / name, dest / name)

    package = repo_root / "automated_security_helper"
    assets = package / "assets"
    generic = shutil.ignore_patterns("__pycache__", "*.pyc")

    def ignore(directory: str, names: list[str]) -> set[str]:
        ignored = set(generic(directory, names))
        if Path(directory) == assets:
            ignored |= ASH_GENERATED_ASSETS & set(names)
        return ignored

    shutil.copytree(package, dest / "automated_security_helper", ignore=ignore)


# The committed, hashed requirement files Dockerfile.ash installs besides ASH's own
# runtime. Regenerated by relock.sh in the operator directory.
E2E_LOCK_FILES = ("ash-build-requirements.txt", "scanner-requirements.txt")
ASH_RUNTIME_LOCK = "ash-runtime.txt"


def ash_runtime_export_argv(output: Path) -> list[str]:
    """`uv export` of ASH's runtime from the repository's uv.lock, with hashes.

    --frozen reads the lock as committed and never re-resolves, so the image gets the
    versions every other ASH test ran against. A lock that no longer satisfies
    pyproject.toml is caught twice over: the repository's own lock check, and the
    image's `pip check` after the ASH wheel is installed with --no-deps.
    """
    return [
        "uv",
        "export",
        "--frozen",
        "--no-dev",
        "--no-emit-project",
        "--no-header",
        "--format",
        "requirements.txt",
        "-o",
        str(output),
    ]


def stage_ash_locks(dest: Path, repo_root: Path = REPO_ROOT) -> None:
    """Write every hashed requirement file Dockerfile.ash installs from into ``dest``."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in E2E_LOCK_FILES:
        shutil.copy(E2E_DIR / name, dest / name)
    runtime = dest / ASH_RUNTIME_LOCK
    result = subprocess.run(
        ash_runtime_export_argv(runtime),
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        raise AssertionError(f"uv export failed ({result.returncode}):\n{result.stderr[-2000:]}")
    text = runtime.read_text()
    # An export of nothing would install nothing and fail later, far from the cause.
    if "--hash=sha256:" not in text or "==" not in text:
        raise AssertionError(f"uv export wrote no hashed pins to {runtime}:\n{text[:500]}")


def context() -> str:
    return f"kind-{CLUSTER_NAME}"


def run(
    argv: list[str],
    *,
    check: bool = True,
    timeout: int = 600,
    stdin: str | None = None,
) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(argv)}", flush=True)
    result = subprocess.run(
        argv, check=False, capture_output=True, text=True, timeout=timeout, input=stdin
    )
    if result.returncode != 0:
        print(result.stdout[-4000:], flush=True)
        print(result.stderr[-4000:], flush=True)
    if check and result.returncode != 0:
        raise AssertionError(
            f"{argv[0]} exited {result.returncode}\n"
            f"stdout: {result.stdout[-2000:]}\nstderr: {result.stderr[-2000:]}"
        )
    return result


def kubectl(
    *args: str, check: bool = True, timeout: int = 300, stdin: str | None = None
) -> subprocess.CompletedProcess:
    return run(
        ["kubectl", "--context", context(), *args],
        check=check,
        timeout=timeout,
        stdin=stdin,
    )


def kubectl_json(*args: str) -> dict:
    return json.loads(kubectl(*args, "-o", "json").stdout)


def kubectl_apply_stdin(body: str) -> None:
    kubectl("apply", "-f", "-", stdin=body)


def wait_for(predicate, *, timeout: int, interval: float = 3.0, what: str = "condition"):
    """Poll *predicate* until truthy, then return its value.

    Returns the value rather than True so a caller can assert on the object it waited
    for without fetching it again, and so the failure message carries the last state
    observed instead of only "timed out".
    """
    deadline = time.monotonic() + timeout
    last = None
    while time.monotonic() < deadline:
        last = predicate()
        if last:
            return last
        time.sleep(interval)
    raise AssertionError(f"timed out after {timeout}s waiting for {what}; last saw {last!r}")


def operator_logs(tail: int = 200) -> str:
    result = kubectl(
        "-n", NAMESPACE, "logs", "deployment/ash-operator", f"--tail={tail}", check=False
    )
    return result.stdout + result.stderr


# The default ``config`` of :func:`apply_scan`: a project name and a MEDIUM threshold.
# A sentinel rather than a literal default, so ``config=None`` can mean "no config".
PROJECT_CONFIG = object()


def apply_fixture_configmap(name: str, fixture: str | Path) -> None:
    """Load a fixture tree into a ConfigMap the scan mounts as its source.

    A ``str`` names a directory under this harness's own ``fixtures/``; a ``Path`` is
    used as given, which is how the shared tree in ``tests/e2e/fixtures`` at the
    repository root gets in.
    """
    directory = fixture if isinstance(fixture, Path) else E2E_DIR / "fixtures" / fixture
    assert directory.is_dir() and any(directory.iterdir()), (
        f"fixture {directory} is missing or empty; a ConfigMap of nothing scans clean"
    )
    # `create --dry-run=client | apply` rather than `create`, so re-running the suite
    # against a fresh cluster and against a warm one behave the same.
    rendered = kubectl(
        "-n",
        NAMESPACE,
        "create",
        "configmap",
        name,
        f"--from-file={directory}",
        "--dry-run=client",
        "-o",
        "yaml",
    ).stdout
    kubectl_apply_stdin(rendered)


def apply_scan(
    name: str,
    *,
    source_configmap: str,
    shard_count: int = 3,
    scanners: list[str] | None = None,
    backoff_limit: int = 0,
    min_severity: str | None = "MEDIUM",
    config: dict | None | object = PROJECT_CONFIG,
    extra_spec: dict | None = None,
) -> None:
    """Create or update an AshScan.

    ``min_severity=None`` and ``config=None`` leave the field out, so the run uses
    ASH's own defaults; the shared contract cases need that to be the same scan every
    other channel runs.
    """
    spec = {
        "image": ASH_IMAGE,
        "imagePullPolicy": "Never",
        "shardCount": shard_count,
        "backoffLimit": backoff_limit,
        "scanServiceAccountName": "ash-scan",
        "source": {"configMap": {"name": source_configmap}},
        "results": {"size": "1Gi", "accessModes": ["ReadWriteOnce"]},
        # One shard at a time, so a ReadWriteOnce claim on a single-node kind
        # cluster works. The partition is unaffected -- it is a function of the
        # roster and the two integers, not of how many pods run at once.
        "parallelism": 1,
        "scanners": scanners or ["bandit", "detect-secrets"],
    }
    if min_severity is not None:
        spec["minSeverity"] = min_severity
    if config is PROJECT_CONFIG:
        spec["config"] = {
            "project_name": name,
            "global_settings": {"severity_threshold": "MEDIUM"},
        }
    elif config is not None:
        spec["config"] = config
    if extra_spec:
        spec.update(extra_spec)
    body = {
        "apiVersion": f"{GROUP}/v1alpha1",
        "kind": "AshScan",
        "metadata": {"name": name, "namespace": NAMESPACE},
        "spec": spec,
    }
    kubectl_apply_stdin(yaml.safe_dump(body))


def scan_status(name: str) -> dict:
    obj = kubectl_json("-n", NAMESPACE, "get", "ashscan", name)
    return obj.get("status") or {}


def wait_terminal(name: str, timeout: int = 900) -> dict:
    # The last observed phase is tracked explicitly rather than left to wait_for's
    # "last saw" reporting. wait_for prints the predicate's return value, which is
    # None for "not yet" -- so a timeout read "last saw None", which looks like an
    # empty .status and sends the reader after the wrong thing. It happened: under
    # nektos/act this timed out and the message implied the operator had written no
    # status at all, when in fact the phase was Scanning and the scan was simply
    # slower than the budget.
    seen: list[str | None] = [None]

    def check():
        status = scan_status(name)
        seen[0] = status.get("phase")
        if seen[0] in TERMINAL:
            return status
        return None

    try:
        status = wait_for(check, timeout=timeout, what=f"AshScan/{name} to reach a terminal phase")
    except AssertionError:
        print(f"=== AshScan/{name} last observed phase: {seen[0]!r} ===")
        print(f"=== raw status: {json.dumps(scan_status(name))[:1500]} ===")
        print("=== operator logs ===")
        print(operator_logs(300))
        print("=== jobs ===")
        kubectl("-n", NAMESPACE, "get", "jobs", check=False)
        kubectl("-n", NAMESPACE, "get", "pods", check=False)
        raise
    # The verdict fields, printed on success too, so a CI log shows what each run
    # actually ended as rather than only that the assertions held.
    summary = {
        key: status.get(key)
        for key in ("phase", "exitCode", "coverageComplete", "coverageGaps", "findings")
    }
    print(f"=== AshScan/{name} terminal: {json.dumps(summary, sort_keys=True)} ===")
    return status


def shard_pods(scan_uid: str) -> list[dict]:
    listing = kubectl_json(
        "-n",
        NAMESPACE,
        "get",
        "pods",
        "-l",
        f"{GROUP}/scan-uid={scan_uid},{GROUP}/role=shard",
    )
    return listing["items"]


def scan_uid(name: str) -> str:
    return kubectl_json("-n", NAMESPACE, "get", "ashscan", name)["metadata"]["uid"]
