# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Example reporter plugin for ASH."""

from pathlib import Path
from typing import Annotated, Literal

from pydantic import Field

from automated_security_helper.base.options import ReporterOptionsBase
from automated_security_helper.base.reporter_plugin import (
    ReporterPluginBase,
    ReporterPluginConfigBase,
)
from automated_security_helper.core.constants import ASH_WORK_DIR_NAME
from automated_security_helper.plugins.decorators import ash_reporter_plugin
from automated_security_helper.models.asharp_model import AshAggregatedResults
from automated_security_helper.utils.log import ASH_LOGGER


class ExampleReporterConfigOptions(ReporterOptionsBase):
    pass


class ExampleReporterConfig(ReporterPluginConfigBase):
    """Configuration for the example reporter."""

    name: Literal["my-example-reporter"] = "my-example-reporter"
    enabled: bool = True
    options: Annotated[
        ExampleReporterConfigOptions,
        Field(description="Configure my-example-reporter"),
    ] = ExampleReporterConfigOptions()


@ash_reporter_plugin
class ExampleReporter(ReporterPluginBase[ExampleReporterConfig]):
    """Example reporter plugin that demonstrates the decorator pattern."""

    def model_post_init(self, context):
        if self.config is None:
            self.config = ExampleReporterConfig()
        self.context.work_dir = self.context.output_dir.joinpath(
            ASH_WORK_DIR_NAME
        ).joinpath(self.config.name)
        return super().model_post_init(context)

    def report(self, model: AshAggregatedResults) -> str:
        """Generate a report from scan results.

        This example reporter simply logs the model and returns a mock report.

        Args:
            model: AshAggregatedResults containing scan results

        Returns:
            str: Report content
        """
        self._pre_report()

        if self.context is None:
            ASH_LOGGER.warning("ExampleReporter: No context provided!")
            return "No context provided"

        ASH_LOGGER.info("ExampleReporter: Generating report")

        # In a real reporter, you would generate a report from the model
        # For this example, we'll just return a mock report
        report_path = Path(self.context.output_dir) / "example_report.txt"

        with open(report_path, mode="w", encoding="utf-8") as f:
            f.write("Example Report\n")
            f.write("=============\n\n")
            f.write(
                "This is an example report generated by the ExampleReporter plugin.\n\n"
            )

            # Add some mock findings
            f.write("Findings:\n")
            f.write("- EXAMPLE-001: Example Finding\n")
            f.write("  Severity: LOW\n")
            f.write(
                "  Description: This is an example finding from the ExampleScanner\n"
            )

        self._post_report()
        return str(report_path)
