# yaml-language-server: $schema=../automated_security_helper/schemas/AshConfig.json
project_name: automated-security-helper
fail_on_findings: true
ash_plugin_modules: []
# ash_plugin_modules:
#   - automated_security_helper.plugin_modules.ash_aws_plugins
external_reports_to_include: []
global_settings:
  severity_threshold: MEDIUM
  suppressions:
    - path: uv.lock
      rule_id: GHSA-2c2j-9gv5-cj73-starlette
      reason: Pending fixed version compatibility from mcp package that depends on starlette
      expiration: "2025-10-01"
    - path: tests/integration/cli/test_mcp_file_tracking_integration.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/test_mcp_integration_simple.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/test_mcp_integration.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/conftest.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: pyproject.toml
      rule_id: SECRET-BASE64-HIGH-ENTROPY-STRING
      reason: This is the project configuration. Findings of this type are false positives.
    - path: automated_security_helper/utils/subprocess_utils.py
      rule_id: python.lang.compatibility.python36.python36-compatibility-Popen1
      reason: This package requires Python3.10 or greater.
    - path: automated_security_helper/utils/subprocess_utils.py
      rule_id: python.lang.compatibility.python36.python36-compatibility-Popen2
      reason: This package requires Python3.10 or greater.
    - path: tests/unit/plugin_modules/ash_aws_plugins/test_cloudwatch_logs_reporter*
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, dummy test data and not an actual secret.
    - path: .github/workflows/run-ash-security-scan.yml
      rule_id: yaml.github-actions.security.run-shell-injection.run-shell-injection
      reason: Troubleshooting swapping from direct injection to evaluating interpolated env vars
      expiration: "2025-10-01"
    - path: tests/**/*.py
      rule_id: B101
      reason: Assert usage expected with Pytest
    - path: tests/utils/*.py
      rule_id: B311
      reason: Test facilities and tooling used to generate randomness during testing.
    - path: tests/unit/utils/*.py
      rule_id: B108
      reason: Temp file path as string, not actual temp dir usage.
    - path: tests/**/*.py
      rule_id: B404
      reason: Subprocess module used across test suite due to the nature of ASH itself being a tool orchestrator. These instances are in test suites and not in the code used at runtime.
    - path: tests/**/*.py
      rule_id: B603
      reason: Subprocess module used across test suite due to the nature of ASH itself being a tool orchestrator. These instances are in test suites and not in the code used at runtime.
    - path: tests/**/*.py
      rule_id: B607
      reason: Mocking and other test mechanisms. These instances are in test suites and not in the code used at runtime.
    - path: docs/content/docs/plugins/aws/index.md
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, not an actual secret
    - path: docs/content/docs/plugins/development-guide.md
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, not an actual secret
    - path: docs/content/docs/testing/examples/*
      reason: Documentation with test code examples focused on brevity.
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/*.*"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/reports/*.json"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/scanners/*.json"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "python.lang.compatibility.python36.python36-compatibility-Popen1"
      path: automated_security_helper/utils/subprocess_utils.py
      reason: "False positive - ASH requires Python 3.10+, compatibility with Python3.6 and less is not required"
    - rule_id: "python.lang.compatibility.python36.python36-compatibility-Popen2"
      path: automated_security_helper/utils/subprocess_utils.py
      reason: "False positive - ASH requires Python 3.10+, compatibility with Python3.6 and less is not required"
  ignore_paths:
    - path: "**/.venv/**"
      reason: Virtual environment, not committed, only 3p content
    - path: "tests/test_data/**"
      reason: This is test data that is used during unit testing only and is not part of the core application.
    - path: "automated_security_helper/assets/ASH_COMMIT*"
      reason: This file is generated by the build process and does not contain any secrets or sensitive information.
    - path: "tests/pytest-temp"
      reason: This is temporary data that is generated during unit testing only and is not part of the core application.
    - path: "**/automated_security_helper/schemas/AshAggregatedResults.json"
      reason: This file is generated by a corresponding Pydantic model and does not contain any secrets or sensitive information. Findings on this file are false positives and should be addressed on the related Pydantic models, not on this JSON file.
    - path: "**/automated_security_helper/schemas/AshConfig.json"
      reason: This file is generated by a corresponding Pydantic model and does not contain any secrets or sensitive information. Findings on this file are false positives and should be addressed on the related Pydantic models, not on this JSON file.
reporters:
  security-hub:
    enabled: false
  # cloudwatch-logs:
  #   enabled: false
  #   options:
  #     aws_region: !ENV ${AWS_REGION:None}
  #     log_group_name: !ENV ${ASH_CLOUDWATCH_LOG_GROUP:None}
  # s3:
  #   enabled: false
  #   options:
  #     aws_region: !ENV ${AWS_REGION:None}
  #     bucket_name: !ENV ${ASH_S3_BUCKET_NAME:None}
  #     bucket_prefix: !ENV ${ASH_S3_BUCKET_PREFIX:None}
  csv:
    enabled: true
  cyclonedx:
    enabled: true
  flat-json:
    enabled: true
  html:
    enabled: true
  junitxml:
    enabled: true
  markdown:
    enabled: true
    options:
      include_detailed_findings: true
      include_findings_table: false
      include_summary: true
      max_detailed_findings: 20
      top_hotspots_limit: 10
      use_collapsible_details: true
  ocsf:
    enabled: true
  sarif:
    enabled: true
  text:
    enabled: true
  spdx:
    enabled: false
  yaml:
    enabled: false
scanners:
  bandit:
    enabled: true
    options:
      confidence_level: all
      ignore_nosec: false
      config_file: .ash/bandit.yaml
  cdk-nag:
    enabled: true
    options:
      nag_packs:
        AwsSolutionsChecks: true
        HIPAASecurityChecks: true
        NIST80053R4Checks: true
        NIST80053R5Checks: true
        PCIDSS321Checks: true
  cfn-nag:
    enabled: true
  checkov:
    enabled: true
    options:
      frameworks:
        - all
      additional_formats: []
      skip_path: []
      config_file: .ash/.checkov.yaml
      severity_threshold: LOW
  detect-secrets:
    enabled: true
  npm-audit:
    enabled: true
  grype:
    enabled: true
    options:
      config_file: .ash/.grype.yaml
  opengrep:
    enabled: true
  semgrep:
    enabled: true
  syft:
    enabled: true
converters:
  archive:
    enabled: true
  jupyter:
    enabled: true
