name: Run ASH
on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: read

jobs:
  ash:
    uses: awslabs/automated-security-helper/.github/workflows/run-ash-security-scan.yml@v3.0.0
    permissions:
      contents: read # Required to read the repository contents in order to scan them with ASH
      checks: write # Required for writing CI check runs
      pull-requests: write # Required for writing comments with scan results to pull requests
      security-events: write # Required for collection of SARIF code scanning results for GitHub Advanced Security checks
    with:
      ash-version: v3.0.0
      fail-on-findings: true
      collect-junit-xml-report: true
      collect-sarif-report: true
      post-pr-comment: true
      verbose: true
      output-dir: '.ash/ash_output'
