"""Turn ASH's own config model into a CRD structural schema.

The requirement is full exposure of ASH's configuration surface, and the trap is
hand-writing a parallel schema that drifts from the models the scan actually
validates against. So ``spec.config`` is *generated* from
``AshConfig.model_json_schema()`` -- one source of truth, regenerated by
``python -m ash_operator.generate_manifests`` and held there by a drift gate, the
same shape the repository already uses for its CDK templates and buildspecs.

Pydantic emits JSON Schema 2020-12. ``apiextensions.k8s.io/v1`` accepts a
restricted OpenAPI-v3-flavoured subset called a *structural schema*. The gap
between the two is real and this module is the translation, with every
transformation recorded so the report can say what could not be expressed rather
than implying everything survived.

What is translated, and why each one is necessary rather than tidy:

``$ref``           Not permitted at all, so every reference is inlined. A
                   reference cycle (``PluginContext`` reaches itself) cannot be
                   inlined at any finite depth, so the cycle point becomes
                   ``x-kubernetes-preserve-unknown-fields`` and is recorded.
``anyOf [T, null]``Pydantic's spelling of ``Optional[T]``. Structural schemas
                   require ``type`` on the specification *outside* the logical
                   junctors, and this shape has none, so it collapses to ``T``
                   plus ``nullable: true``.
``const``          Not in ``JSONSchemaProps``; becomes a single-member ``enum``.
``exclusiveMinimum``JSON Schema 2020-12 makes it a number. OpenAPI v3.0, which
                   apiextensions follows, makes it a boolean paired with
                   ``minimum``. Left as a number the API server rejects the CRD.
``additionalProperties``Mutually exclusive with ``properties``. Pydantic emits
                   ``additionalProperties: false`` for every ``extra="forbid"``
                   model, which is most of them. Dropped where ``properties`` is
                   present -- and nothing is lost, because CRD pruning already
                   removes unknown fields, which is stronger than rejecting them
                   at validation time only.
``default``        **Dropped everywhere**, and this is a decision rather than a
                   limitation. Keeping them would make the API server write
                   ASH's entire default config into every AshScan at admission,
                   which freezes those defaults at creation time: upgrade the ASH
                   image to a version that changed one, and the CR keeps
                   overriding it with the old value invisibly. Omitting them
                   means the CR carries only what its author wrote, and ASH's own
                   models supply the rest at scan time -- which is where they
                   belong.
``title``          Dropped. It restates the property name and it is the single
                   largest contributor to the generated size.

Naming: ASH's keys stay exactly as ASH spells them -- ``snake_case`` and one
hyphenated key, ``mcp-resource-management``. This breaks the Kubernetes camelCase
convention, on purpose, and only inside ``spec.config``. That block is copied
verbatim into the ConfigMap that becomes ``.ash.yaml``, so a key spelled
differently in the CR than in the file would mean the operator rewriting an
adopter's config, and a config the operator rewrites is a config nobody can
diff against ASH's documentation. Every field the *operator* owns is camelCase.
"""

from __future__ import annotations

import copy
import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Keywords apiextensions' JSONSchemaProps understands. Anything else is dropped
# and recorded; silently passing an unknown key through makes the API server
# reject the whole CRD with a message that names the key and not the reason.
_KNOWN_KEYWORDS = frozenset(
    {
        "additionalItems",
        "additionalProperties",
        "allOf",
        "anyOf",
        "default",
        "description",
        "enum",
        "example",
        "exclusiveMaximum",
        "exclusiveMinimum",
        "externalDocs",
        "format",
        "id",
        "items",
        "maxItems",
        "maxLength",
        "maxProperties",
        "maximum",
        "minItems",
        "minLength",
        "minProperties",
        "minimum",
        "multipleOf",
        "not",
        "nullable",
        "oneOf",
        "pattern",
        "patternProperties",
        "properties",
        "required",
        "title",
        "type",
        "uniqueItems",
        "x-kubernetes-embedded-resource",
        "x-kubernetes-int-or-string",
        "x-kubernetes-list-map-keys",
        "x-kubernetes-list-type",
        "x-kubernetes-map-type",
        "x-kubernetes-preserve-unknown-fields",
        "x-kubernetes-validations",
    }
)

# Dropped on purpose rather than because they are unknown; see module docstring.
_DELIBERATE_DROPS = frozenset({"default", "title"})

_PRESERVE = {"x-kubernetes-preserve-unknown-fields": True}


@dataclass
class Translation:
    """What the translation had to do, so the result can be described honestly."""

    cycles: list[str] = field(default_factory=list)
    unexpressible: list[dict[str, str]] = field(default_factory=list)
    dropped_keywords: dict[str, int] = field(default_factory=dict)
    collapsed_optionals: int = 0
    const_to_enum: int = 0
    exclusive_bounds_rewritten: int = 0
    additional_properties_dropped: int = 0
    # Which of the two schema sources was used, and a digest of it. Both land in the
    # committed report so a reviewer can tell a translation change from an upstream
    # model change without re-running the generator.
    source: str = "unknown"
    source_digest: str = ""

    def note_drop(self, keyword: str) -> None:
        self.dropped_keywords[keyword] = self.dropped_keywords.get(keyword, 0) + 1

    def note_unexpressible(self, pointer: str, reason: str) -> None:
        self.unexpressible.append({"path": pointer, "reason": reason})

    def as_report(self) -> dict[str, Any]:
        return {
            # Not the ASH version: see ash_config_schema_digest for why a version
            # here would make the drift gate fail for two byte-identical schemas.
            "sourceSchemaSha256": self.source_digest,
            "referenceCycles": sorted(set(self.cycles)),
            "unexpressible": self.unexpressible,
            "droppedKeywords": dict(sorted(self.dropped_keywords.items())),
            "collapsedOptionals": self.collapsed_optionals,
            "constRewrittenToEnum": self.const_to_enum,
            "exclusiveBoundsRewritten": self.exclusive_bounds_rewritten,
            "additionalPropertiesDroppedAlongsideProperties": (self.additional_properties_dropped),
        }


def _is_null_branch(node: Any) -> bool:
    return isinstance(node, dict) and node.get("type") == "null" and len(node) == 1


def _inline_refs(
    node: Any, defs: dict[str, Any], seen: tuple[str, ...], report: Translation, pointer: str
) -> Any:
    """Dereference ``$ref`` depth-first, replacing cycles with a preserve marker."""
    if isinstance(node, list):
        return [
            _inline_refs(item, defs, seen, report, f"{pointer}/{i}") for i, item in enumerate(node)
        ]
    if not isinstance(node, dict):
        return node
    if "$ref" in node:
        name = str(node["$ref"]).rsplit("/", 1)[-1]
        siblings = {k: v for k, v in node.items() if k != "$ref"}
        if name in seen:
            report.cycles.append(name)
            report.note_unexpressible(
                pointer,
                f"{name} refers to itself, directly or through another definition. A "
                f"structural schema cannot hold a cycle because $ref is not allowed "
                f"and inlining never terminates, so this subtree accepts any object "
                f"and is validated by ASH at scan time instead.",
            )
            return {"type": "object", **_PRESERVE}
        target = defs.get(name)
        if target is None:
            report.note_unexpressible(
                pointer, f"$ref to unknown definition {name!r}; subtree left unvalidated"
            )
            return {"type": "object", **_PRESERVE}
        inlined = _inline_refs(target, defs, seen + (name,), report, pointer)
        if siblings:
            merged = copy.deepcopy(inlined) if isinstance(inlined, dict) else inlined
            if isinstance(merged, dict):
                merged.update(_inline_refs(siblings, defs, seen, report, pointer))
                return merged
        return inlined
    return {
        key: _inline_refs(value, defs, seen, report, f"{pointer}/{key}")
        for key, value in node.items()
        if key != "$defs"
    }


def _decide_additional_properties(
    node: dict[str, Any], report: Translation, pointer: str
) -> dict[str, Any]:
    """Resolve ``additionalProperties`` before the node is recursed into.

    ``properties`` and ``additionalProperties`` are mutually exclusive in a
    structural schema, and pydantic emits both on every ``extra="forbid"`` model
    that also has a typed catch-all -- which is how ASH spells its three plugin
    maps (``scanners``, ``reporters``, ``converters``): the ten built-ins as
    declared properties, plus a schema for whatever a plugin module registers.

    Dropping ``additionalProperties`` and stopping there would have been wrong in a
    way that is easy to miss. CRD pruning removes undeclared fields *silently*, so
    an adopter configuring a custom scanner under ``scanners.my-scanner`` would
    watch the API server delete it and then get a scan that ran the plugin with
    its defaults. So where the catch-all admits anything, the node keeps its
    declared properties and gains
    ``x-kubernetes-preserve-unknown-fields: true``: known keys stay validated,
    unknown keys survive to reach ``.ash.yaml``. What is lost is only the
    *schema* the catch-all named, which ASH re-checks when it loads the config.

    Resolved before recursion so the decision is recorded once, at the node that
    made it, instead of the discarded subtree filing findings of its own.
    """
    if "additionalProperties" not in node:
        return node
    extra = node["additionalProperties"]
    trimmed = {k: v for k, v in node.items() if k != "additionalProperties"}
    if "properties" not in node:
        # A plain map type. Expressible exactly, so keep it -- except for the two
        # degenerate spellings.
        if extra is True:
            return {**trimmed, **_PRESERVE}
        if extra is False:
            return {**trimmed, "type": trimmed.get("type", "object")}
        return node
    report.additional_properties_dropped += 1
    if extra is False:
        # "Reject unknown keys". CRD pruning deletes them instead, which is
        # stronger, so nothing is lost and nothing needs recording beyond the count.
        return trimmed
    report.note_unexpressible(
        pointer,
        "this object declares named properties and a schema for any others; a "
        "structural schema permits only one of the two. The named properties stay "
        "validated and unknown keys are preserved rather than pruned, so a custom "
        "plugin's config still reaches .ash.yaml -- but its values are checked by "
        "ASH when it loads the config, not by the API server.",
    )
    return {**trimmed, **_PRESERVE}


def _structural(node: Any, report: Translation, pointer: str = "") -> Any:
    """Rewrite one inlined JSON Schema node into a structural schema node."""
    if not isinstance(node, dict):
        return node

    out: dict[str, Any] = {}
    nullable = False
    node = _decide_additional_properties(node, report, pointer)

    # ── Optional[T] ──────────────────────────────────────────────────────────
    for junctor in ("anyOf", "oneOf"):
        branches = node.get(junctor)
        if not isinstance(branches, list):
            continue
        non_null = [b for b in branches if not _is_null_branch(b)]
        if len(non_null) < len(branches):
            nullable = True
        if len(non_null) == 1:
            report.collapsed_optionals += 1
            merged = dict(non_null[0])
            for key, value in node.items():
                if key != junctor and key not in merged:
                    merged[key] = value
            result = _structural(merged, report, pointer)
            if isinstance(result, dict):
                result["nullable"] = True if nullable else result.get("nullable", False)
                if not result["nullable"]:
                    result.pop("nullable", None)
            return result
        if len(non_null) > 1:
            branch_types = {b.get("type") for b in non_null if isinstance(b, dict) and "type" in b}
            if len(branch_types) != 1 or None in branch_types:
                report.note_unexpressible(
                    pointer,
                    f"a union of {len(non_null)} branches with types "
                    f"{sorted(str(t) for t in branch_types)} -- a structural schema "
                    f"needs one type outside the junctor, so this subtree accepts any "
                    f"value and ASH validates it at scan time.",
                )
                preserved = {**_PRESERVE}
                if node.get("description"):
                    preserved["description"] = node["description"]
                return preserved
            # Same type across branches: hoist it and keep the union. Structural
            # schemas forbid default/nullable/additionalProperties *inside* a
            # junctor, so the branches are stripped to their constraints.
            hoisted = branch_types.pop()
            cleaned = []
            for branch in non_null:
                sub = _structural(branch, report, pointer)
                if isinstance(sub, dict):
                    for forbidden in ("default", "nullable", "additionalProperties", "type"):
                        sub.pop(forbidden, None)
                    if sub:
                        cleaned.append(sub)
            out["type"] = hoisted
            if cleaned:
                out[junctor] = cleaned
            if node.get("description"):
                out["description"] = node["description"]
            if nullable:
                out["nullable"] = True
            return out

    for key, value in node.items():
        if key in _DELIBERATE_DROPS:
            report.note_drop(key)
            continue
        if key == "const":
            report.const_to_enum += 1
            out["enum"] = [value]
            continue
        if (
            key == "exclusiveMinimum"
            and isinstance(value, (int, float))
            and not isinstance(value, bool)
        ):
            report.exclusive_bounds_rewritten += 1
            out["minimum"] = value
            out["exclusiveMinimum"] = True
            continue
        if (
            key == "exclusiveMaximum"
            and isinstance(value, (int, float))
            and not isinstance(value, bool)
        ):
            report.exclusive_bounds_rewritten += 1
            out["maximum"] = value
            out["exclusiveMaximum"] = True
            continue
        if key == "type" and isinstance(value, list):
            non_null_types = [t for t in value if t != "null"]
            if len(non_null_types) != 1:
                report.note_unexpressible(
                    pointer,
                    f"type is the list {value!r}; a structural schema allows one type "
                    f"per node, so this subtree is left unvalidated.",
                )
                return {**_PRESERVE}
            nullable = nullable or len(non_null_types) < len(value)
            out["type"] = non_null_types[0]
            continue
        if key not in _KNOWN_KEYWORDS:
            report.note_drop(key)
            continue
        if key == "properties" and isinstance(value, dict):
            out["properties"] = {
                name: _structural(sub, report, f"{pointer}/properties/{name}")
                for name, sub in value.items()
            }
            continue
        if key in ("items", "not", "additionalProperties") and isinstance(value, dict):
            out[key] = _structural(value, report, f"{pointer}/{key}")
            continue
        if key in ("allOf", "anyOf", "oneOf") and isinstance(value, list):
            out[key] = [
                _structural(sub, report, f"{pointer}/{key}/{i}") for i, sub in enumerate(value)
            ]
            continue
        out[key] = copy.deepcopy(value)

    # ── every node needs a type ──────────────────────────────────────────────
    if "type" not in out and "x-kubernetes-preserve-unknown-fields" not in out:
        if "properties" in out or "additionalProperties" in out:
            out["type"] = "object"
        elif "items" in out:
            out["type"] = "array"
        elif "enum" in out:
            inferred = {type(v).__name__ for v in out["enum"]}
            out["type"] = "string" if inferred == {"str"} else None
            if out["type"] is None:
                out.pop("type")
                report.note_unexpressible(
                    pointer, f"enum of mixed types {sorted(inferred)}; left unvalidated"
                )
                out.update(_PRESERVE)
        else:
            report.note_unexpressible(
                pointer,
                "no type and no properties -- the model accepts any value here, so "
                "the CRD does too.",
            )
            out.update(_PRESERVE)

    if nullable:
        out["nullable"] = True
    if out.get("type") == "array" and "items" not in out:
        # A typed array with no item schema is non-structural.
        out["items"] = {**_PRESERVE}
    return out


# The repository's committed copy of the same schema, written by
# automated_security_helper/schemas/generate_schemas.py from the same models and held
# fresh by the repository's own pre-commit hook and CI.
_COMMITTED_SCHEMA = (
    Path(__file__).resolve().parents[3] / "automated_security_helper" / "schemas" / "AshConfig.json"
)


def ash_config_json_schema() -> tuple[dict[str, Any], str]:
    """Return ``AshConfig``'s JSON Schema and where it came from.

    Two sources, in order:

    1. ``AshConfig.model_json_schema()`` from an importable ASH -- authoritative.
    2. The committed ``automated_security_helper/schemas/AshConfig.json``, which the
       repository generates from that same model and keeps fresh with its own gate.

    The fallback is not a convenience. The operator never imports ASH at runtime, so
    requiring it to run the *tests* would mean either installing ASH's whole
    dependency tree into a lint job or skipping the schema tests there -- and a
    skipped structural-schema test is how an unappliable CRD ships. Measured under
    ``nektos/act``: with only the operator installed, seven CRD-schema tests errored
    with ``ModuleNotFoundError: No module named 'automated_security_helper'``, which
    a ``-q`` summary reports on a line nobody reads.

    ``tests/test_crd_schema.py`` asserts the two sources agree whenever both are
    available, so the fallback cannot quietly drift from the model.
    """
    try:
        from automated_security_helper.config.ash_config import AshConfig
    except ImportError:
        pass
    else:
        return AshConfig.model_json_schema(), "model"
    if _COMMITTED_SCHEMA.is_file():
        with open(_COMMITTED_SCHEMA) as handle:
            return json.load(handle), "committed"
    raise RuntimeError(
        f"neither an importable AshConfig nor a committed schema at "
        f"{_COMMITTED_SCHEMA} was found. The CRD cannot be generated without one of "
        f"them, and emitting a CRD with an empty spec.config would be worse: the API "
        f"server would prune every config field an adopter wrote."
    )


def ash_config_schema_digest(schema: dict[str, Any]) -> str:
    """A short digest of the input schema, for the generated CRD's annotation.

    Deliberately not the ASH *version*. An annotation carrying the version would
    differ between a CRD generated with ASH importable and one generated from the
    committed schema, and the drift gate would then fail for two people who produced
    byte-identical schemas. A digest of the schema itself is the same either way --
    which the agreement test makes true rather than assumed -- and it answers the
    question the annotation exists for: which ASH config surface is this CRD from.

    Every ``default`` keyword is left out of the hash. The CRD drops all of them
    (``_DELIBERATE_DROPS``), so they are not part of the surface it carries, and two
    of them are not even the same on every machine: opengrep's and semgrep's
    ``enabled`` default is ``platform.system().lower() != "windows"``, evaluated when
    ASH is imported. Hashing them made the generator emit different annotations on
    Windows, so a ``--check`` there failed against the committed files, and a
    regeneration there would have broken every other platform's check.
    """
    canonical = json.dumps(_without_defaults(schema), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()[:16]


# Keywords whose value maps names to subschemas, so a key inside one is a field or
# definition name (a field may be called "default") rather than a keyword.
_NAME_MAPS = frozenset({"properties", "patternProperties", "$defs", "definitions"})
# Keywords whose value is data, not a subschema; nothing inside them is a keyword.
_DATA_VALUES = frozenset({"enum", "const", "examples", "example"})


def _without_defaults(node: Any) -> Any:
    """``node`` with every ``default`` keyword removed, wherever a subschema can sit."""
    if isinstance(node, list):
        return [_without_defaults(item) for item in node]
    if not isinstance(node, dict):
        return node
    out: dict[str, Any] = {}
    for key, value in node.items():
        if key == "default":
            continue
        if key in _NAME_MAPS and isinstance(value, dict):
            out[key] = {name: _without_defaults(sub) for name, sub in value.items()}
        elif key in _DATA_VALUES:
            out[key] = value
        else:
            out[key] = _without_defaults(value)
    return out


def build_config_schema(
    source_schema: dict[str, Any] | None = None,
) -> tuple[dict[str, Any], Translation]:
    """Return the structural schema for ``spec.config`` plus a translation report."""
    if source_schema is None:
        source_schema, origin = ash_config_json_schema()
    else:
        origin = "supplied"
    raw = copy.deepcopy(source_schema)
    defs = raw.get("$defs", {})
    report = Translation()
    root = raw
    if "$ref" in raw and "properties" not in raw:
        root = {k: v for k, v in raw.items() if k != "$defs"}
    inlined = _inline_refs(root, defs, (), report, "")
    schema = _structural(inlined, report, "")
    if not isinstance(schema, dict):  # pragma: no cover - AshConfig is an object
        raise TypeError(f"AshConfig did not translate to an object: {type(schema)}")
    schema["description"] = (
        "ASH configuration, in ASH's own spelling. Written verbatim into the "
        "ConfigMap the scan pods read as ASH_CONFIG, so this block is "
        "interchangeable with a .ash.yaml file. Generated from "
        "AshConfig.model_json_schema(); do not edit by hand."
    )
    # Not every AshConfig field is meaningful under the operator, and saying so in
    # the schema is better than letting an adopter set one that the operator then
    # ignores or overrides.
    _annotate_overridden(schema)
    report.source = origin
    report.source_digest = ash_config_schema_digest(source_schema)
    return schema, report


_OVERRIDDEN_BY_OPERATOR = {
    "fail_on_findings": (
        "Set on `ashx merge` from spec.failOnFindings instead. A shard's exit code "
        "is discarded, so setting it here would read as a gate that never fires."
    ),
    "fail_on_incomplete_scanners": (
        "Set on `ashx merge` from spec.failOnIncompleteScanners instead, for the "
        "same reason as fail_on_findings."
    ),
}


def _annotate_overridden(schema: dict[str, Any]) -> None:
    props = schema.get("properties") or {}
    for name, note in _OVERRIDDEN_BY_OPERATOR.items():
        node = props.get(name)
        if isinstance(node, dict):
            existing = node.get("description", "")
            node["description"] = f"{existing}\n\nIGNORED BY THE OPERATOR: {note}".strip()
