# Get Python Image
FROM public.ecr.aws/bitnami/python:latest

# Instal prerequisites
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir bandit nbconvert jupyterlab && \
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app
VOLUME /app

CMD bash -C /utils/py-docker-execute.sh
