# Get Ubuntu Image
#FROM public.ecr.aws/bitnami/python:latest
FROM --platform=linux/amd64 public.ecr.aws/bitnami/python:latest

# Install prerequisites
RUN apt-get update && \
    apt-get install -y git && \
    apt-get upgrade -y

# Clone git-secrets directory
RUN git clone https://github.com/awslabs/git-secrets.git && \
    cd git-secrets && \
    make install

WORKDIR /app
VOLUME /app

CMD bash -C /utils/git-docker-execute.sh
