# Get NPM Image
FROM public.ecr.aws/docker/library/node:18.0.0
ARG OFFLINE="NO"
ENV BUILD_DATE_EPOCH="${BUILD_DATE_EPOCH}"

ENV BUILD_DATE_EPOCH="${BUILD_DATE_EPOCH}"
ENV OFFLINE="${OFFLINE}"
#
# Make sure the default dirs are initialized
#
RUN mkdir -p /src && \
    mkdir -p /out && \
    mkdir -p /run/scan/src \
    mkdir -p /ash

WORKDIR /src
VOLUME /src

CMD bash -C /utils/js-docker-execute.sh
