# Get Python Image
FROM --platform=linux/amd64 public.ecr.aws/bitnami/python:3.11

# Allow for wider, more readable Semgrep output
ENV COLUMNS 120

# Install prerequisites
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin && \
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin && \
    python3 -m pip install semgrep

#
# Make sure the default dirs are initialized
#
RUN mkdir -p /src && \
    mkdir -p /out && \
    mkdir -p /run/scan/src \
    mkdir -p /ash

WORKDIR /src
VOLUME /src

CMD bash -C /utils/grype-docker-execute.sh
