# Get Ubuntu Image
FROM --platform=linux/amd64 public.ecr.aws/bitnami/python:3.11

# Install prerequisites
RUN apt-get update && \
    apt-get install -y git tree && \
    apt-get upgrade -y

# Clone git-secrets directory
RUN git clone https://github.com/awslabs/git-secrets.git && \
    cd git-secrets && \
    make install

#
# Make sure the default dirs are initialized
#
RUN mkdir -p /src && \
    mkdir -p /out && \
    mkdir -p /run/scan/src \
    mkdir -p /ash

WORKDIR /src
VOLUME /src

CMD bash -C /utils/git-docker-execute.sh
