# Get Ubuntu Image
FROM --platform=linux/amd64 public.ecr.aws/bitnami/python:3.11
ARG OFFLINE="NO"
ENV BUILD_DATE_EPOCH="${BUILD_DATE_EPOCH}"

ENV BUILD_DATE_EPOCH="${BUILD_DATE_EPOCH}"
ENV OFFLINE="${OFFLINE}"

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Instal prerequisites
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ruby-full && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install -U checkov && gem install cfn-nag

#
# Make sure the default dirs are initialized
#
RUN mkdir -p /src && \
    mkdir -p /out && \
    mkdir -p /run/scan/src \
    mkdir -p /ash

WORKDIR /src

CMD bash -C /utils/yaml-docker-execute.sh
