# Get Ubuntu Image
#FROM public.ecr.aws/bitnami/python:latest
FROM --platform=linux/amd64 public.ecr.aws/bitnami/python:latest

# Instal prerequisites
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential git
RUN apt-get install -y git
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Clone git-secrets directorya
RUN git clone https://github.com/awslabs/git-secrets.git && \
    cd git-secrets && \
    make install

WORKDIR /app
VOLUME /app

CMD bash -C /utils/git-docker-execute.sh
