# Get Ubuntu Image
#FROM public.ecr.aws/ubuntu/ubuntu:latest
FROM public.ecr.aws/ubuntu/ubuntu:20.04
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Instal prerequisites
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3 python3-pip curl && \
    rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt -y install nodejs
RUN npm install -g aws-cdk
RUN python3 -m pip install -U aws-cdk-lib cdk-nag jinja2
WORKDIR /app

CMD bash -C /utils/cdk-docker-execute.sh
