"""Unit tests for the config init command — verifies generated configs pass validation."""

import yaml
import pytest
from typer.testing import CliRunner

from automated_security_helper.cli.config import config_app
from automated_security_helper.config.config_validator import ConfigValidator


@pytest.fixture
def cli_runner():
    return CliRunner()


@pytest.fixture
def config_path(tmp_path):
    return tmp_path / ".ash" / ".ash.yaml"


class TestConfigInitValidation:
    """Ensure `ash config init` produces a config that passes `ash config validate`."""

    def test_init_generates_valid_config(self, cli_runner, config_path):
        """Config generated by init must pass the validator with zero errors."""
        result = cli_runner.invoke(config_app, ["init", "--config", str(config_path)])
        assert result.exit_code == 0, f"init failed: {result.output}"
        assert config_path.exists()

        is_valid, errors = ConfigValidator.validate_config_file(config_path)
        assert is_valid, f"Generated config failed validation: {errors}"
        assert errors == []

    def test_init_excludes_internal_top_level_fields(self, cli_runner, config_path):
        """Internal fields like 'build' and 'mcp-resource-management' must not appear."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        for field in ConfigValidator.INVALID_TOP_LEVEL_FIELDS:
            assert field not in config_data, (
                f"Internal top-level field '{field}' leaked into generated config"
            )

    def test_init_excludes_internal_scanner_fields(self, cli_runner, config_path):
        """Scanner entries must not contain internal-only fields like 'name'."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        scanners = config_data.get("scanners", {})
        for scanner_name, scanner_cfg in scanners.items():
            if not isinstance(scanner_cfg, dict):
                continue
            for field in ConfigValidator.INTERNAL_SCANNER_FIELDS:
                assert field not in scanner_cfg, (
                    f"Scanner '{scanner_name}' contains internal field '{field}'"
                )

    def test_init_excludes_internal_reporter_fields(self, cli_runner, config_path):
        """Reporter entries must not contain internal-only fields like 'name' or 'extension'."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        reporters = config_data.get("reporters", {})
        for reporter_name, reporter_cfg in reporters.items():
            if not isinstance(reporter_cfg, dict):
                continue
            for field in ConfigValidator.INTERNAL_REPORTER_FIELDS:
                assert field not in reporter_cfg, (
                    f"Reporter '{reporter_name}' contains internal field '{field}'"
                )

    def test_init_excludes_internal_converter_fields(self, cli_runner, config_path):
        """Converter entries must not contain internal-only fields like 'name'."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        converters = config_data.get("converters", {})
        for converter_name, converter_cfg in converters.items():
            if not isinstance(converter_cfg, dict):
                continue
            for field in ConfigValidator.INTERNAL_CONVERTER_FIELDS:
                assert field not in converter_cfg, (
                    f"Converter '{converter_name}' contains internal field '{field}'"
                )

    def test_init_includes_required_fields(self, cli_runner, config_path):
        """Generated config must include all required top-level fields."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        for field in ConfigValidator.REQUIRED_TOP_LEVEL_FIELDS:
            assert field in config_data, (
                f"Required field '{field}' missing from generated config"
            )

    def test_init_only_contains_valid_top_level_fields(self, cli_runner, config_path):
        """Every top-level key in the generated config must be in the valid set."""
        cli_runner.invoke(config_app, ["init", "--config", str(config_path)])

        with open(config_path) as f:
            config_data = yaml.safe_load(f)

        for field in config_data:
            assert field in ConfigValidator.VALID_TOP_LEVEL_FIELDS, (
                f"Unexpected top-level field '{field}' in generated config"
            )
