# generated by datamodel-codegen:
#   filename:  amazonq-agent.schema.json
#   timestamp: 2026-05-11T20:39:02+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Oauth(BaseModel):
    """
    OAuth configuration for this server
    """

    redirectUri: str | None = None
    """
    Custom redirect URI for OAuth flow (e.g., "127.0.0.1:7778"). If not specified, a random available port will be assigned by the OS
    """


class HookCommand(BaseModel):
    command: str
    """
    The command to run when the hook is triggered
    """


class HookCommands(RootModel[list[HookCommand]]):
    root: list[HookCommand]


class TransportType(StrEnum):
    stdio = 'stdio'
    """
    Standard input/output transport (default)
    """
    http = 'http'
    """
    HTTP transport for web-based communication
    """


class McpServers(BaseModel):
    type: TransportType | None = 'stdio'
    """
    The type of transport the mcp server is expecting. For http transport, only url (for now) is taken into account
    """
    url: str | None = ''
    """
    The URL endpoint for HTTP-based MCP servers
    """
    headers: dict[str, str] | None = {}
    """
    HTTP headers to include when communicating with HTTP-based MCP servers
    """
    oauthScopes: list[str] | None = ['openid', 'email', 'profile', 'offline_access']
    """
    Scopes with which oauth is done
    """
    oauth: Oauth | None = None
    """
    OAuth configuration for this server
    """
    command: str
    """
    The command string used to initialize the mcp server
    """
    args: list[str] | None = []
    """
    A list of arguments to be used to run the command with
    """
    env: dict[str, Any] | None = None
    """
    A list of environment variables to run the command with
    """
    timeout: conint(ge=0) | None = 120000
    """
    Timeout for each mcp request in ms
    """
    disabled: bool | None = False
    """
    A boolean flag to denote whether or not to load this mcp server
    """


class Hooks(BaseModel):
    """
    Commands to run when a chat session is created
    """

    userPromptSubmit: HookCommands | None = None
    agentSpawn: HookCommands | None = None


class Agent(BaseModel):
    """
    An Agent is a declarative way of configuring a given instance of q chat.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str | None = Field(default=None, alias='$schema')
    """
    The schema to use for validating the agent
    """
    name: str
    """
    Name of the agent
    """
    description: str | None = None
    """
    This field is not model facing and is mostly here for users to discern between agents
    """
    prompt: str | None = None
    """
    The intention for this field is to provide high level context to the
    agent. This should be seen as the same category of context as a system prompt.
    Supports both inline text and file:// URIs to reference external files.
    Example: "file://./my-prompt.md" (relative to agent config file)
    """
    mcpServers: dict[str, McpServers] | None = Field(default={}, validate_default=True)
    """
    Configuration for Model Context Protocol (MCP) servers
    """
    tools: list[str] | None = []
    """
    List of tools the agent can see. Use \\"@{MCP_SERVER_NAME}/tool_name\\" to specify tools from
    mcp servers. To include all tools from a server, use \\"@{MCP_SERVER_NAME}\\"
    """
    toolAliases: dict[str, str] | None = {}
    """
    Tool aliases for remapping tool names
    """
    allowedTools: list[str] | None = []
    """
    List of tools the agent is explicitly allowed to use
    """
    resources: list[constr(pattern=r'^(file://)')] | None = []
    """
    Files to include in the agent's context
    """
    hooks: Hooks | None = Field(default={}, validate_default=True)
    """
    Commands to run when a chat session is created
    """
    toolsSettings: dict[str, dict[str, Any]] | None = {}
    """
    Settings for specific tools. These are mostly for native tools. The actual schema differs by
    tools and is documented in detail in our documentation
    """
    useLegacyMcpJson: bool | None = False
    """
    Whether or not to include the legacy ~/.aws/amazonq/mcp.json in the agent
    You can reference tools brought in by these servers as just as you would with the servers
    you configure in the mcpServers field in this config
    """
    model: str | None = None
    """
    The model ID to use for this agent. If not specified, uses the default model.
    """
