# generated by datamodel-codegen:
#   filename:  continue-config.schema.json
#   timestamp: 2026-05-11T18:42:34+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, RootModel, constr


class Metadata(BaseModel):
    tags: str | None = None
    sourceCodeUrl: str | None = None
    description: str | None = None
    author: str | None = None
    license: str | None = None
    iconUrl: str | None = None


class ClientCertificate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cert: str
    key: str
    passphrase: str | None = None


class RequestOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class Role(StrEnum):
    chat = 'chat'
    autocomplete = 'autocomplete'
    embed = 'embed'
    rerank = 'rerank'
    edit = 'edit'
    apply = 'apply'
    summarize = 'summarize'
    subagent = 'subagent'


class DefaultCompletionOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contextLength: float | None = None
    maxTokens: float | None = None
    temperature: float | None = None
    topP: float | None = None
    topK: float | None = None
    minP: float | None = None
    presencePenalty: float | None = None
    frequencyPenalty: float | None = None
    stop: list[str] | None = None
    n: float | None = None
    reasoning: bool | None = None
    reasoningBudgetTokens: float | None = None
    promptCaching: bool | None = None
    stream: bool | None = None
    keepAlive: float | None = None


class CacheBehavior(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cacheSystemMessage: bool | None = None
    cacheConversation: bool | None = None


class RequestOptions1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class EmbedOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxChunkSize: float | None = None
    maxBatchSize: float | None = None
    embeddingPrefixes: dict[str, str] | None = None


class SystemMessageDescription(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prefix: str | None = None
    exampleArgs: list[list[str | str | float]] | None = None


class ToolOverrides(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    displayTitle: str | None = None
    wouldLikeTo: str | None = None
    isCurrently: str | None = None
    hasAlready: str | None = None
    systemMessageDescription: SystemMessageDescription | None = None
    disabled: bool | None = None


class ChatOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseSystemMessage: str | None = None
    baseAgentSystemMessage: str | None = None
    basePlanSystemMessage: str | None = None
    toolOverrides: dict[str, ToolOverrides] | None = None


class Chat(StrEnum):
    llama2 = 'llama2'
    alpaca = 'alpaca'
    zephyr = 'zephyr'
    phi2 = 'phi2'
    phind = 'phind'
    anthropic = 'anthropic'
    chatml = 'chatml'
    none = 'none'
    openchat = 'openchat'
    deepseek = 'deepseek'
    xwin_coder = 'xwin-coder'
    neural_chat = 'neural-chat'
    codellama_70b = 'codellama-70b'
    llava = 'llava'
    gemma = 'gemma'
    granite = 'granite'
    llama3 = 'llama3'
    codestral = 'codestral'


class PromptTemplates(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apply: str | None = None
    chat: Chat | None = None
    edit: str | None = None
    autocomplete: str | None = None


class AutocompleteOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    disable: bool | None = None
    maxPromptTokens: float | None = None
    debounceDelay: float | None = None
    modelTimeout: float | None = None
    maxSuffixPercentage: float | None = None
    prefixPercentage: float | None = None
    transform: bool | None = None
    template: str | None = None
    onlyMyCode: bool | None = None
    useCache: bool | None = None
    useImports: bool | None = None
    useRecentlyEdited: bool | None = None
    useRecentlyOpened: bool | None = None
    experimental_includeClipboard: bool | None = None
    experimental_includeRecentlyVisitedRanges: bool | None = None
    experimental_includeRecentlyEditedRanges: bool | None = None
    experimental_includeDiff: bool | None = None
    experimental_enableStaticContextualization: bool | None = None


class Models(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    model: str
    apiKey: str | None = None
    apiBase: str | None = None
    contextLength: float | None = None
    maxStopWords: float | None = None
    roles: list[Role] | None = None
    capabilities: (
        list[Literal['tool_use'] | Literal['image_input'] | Literal['next_edit'] | str]
        | None
    ) = None
    defaultCompletionOptions: DefaultCompletionOptions | None = None
    cacheBehavior: CacheBehavior | None = None
    requestOptions: RequestOptions1 | None = None
    embedOptions: EmbedOptions | None = None
    chatOptions: ChatOptions | None = None
    promptTemplates: PromptTemplates | None = None
    useLegacyCompletionsEndpoint: bool | None = None
    useResponsesApi: bool | None = None
    env: dict[str, str | bool | float] | None = None
    autocompleteOptions: AutocompleteOptions | None = None
    provider: Literal['continue-proxy']
    apiKeyLocation: str | None = None
    envSecretLocations: dict[str, str] | None = None
    orgScopeId: str | None
    onPremProxyUrl: str | None


class RequestOptions2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class ToolOverrides1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    displayTitle: str | None = None
    wouldLikeTo: str | None = None
    isCurrently: str | None = None
    hasAlready: str | None = None
    systemMessageDescription: SystemMessageDescription | None = None
    disabled: bool | None = None


class ChatOptions1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseSystemMessage: str | None = None
    baseAgentSystemMessage: str | None = None
    basePlanSystemMessage: str | None = None
    toolOverrides: dict[str, ToolOverrides1] | None = None


class PromptTemplates1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apply: str | None = None
    chat: Chat | None = None
    edit: str | None = None
    autocomplete: str | None = None


class Models1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    model: str
    apiKey: str | None = None
    apiBase: str | None = None
    contextLength: float | None = None
    maxStopWords: float | None = None
    roles: list[Role] | None = None
    capabilities: (
        list[Literal['tool_use'] | Literal['image_input'] | Literal['next_edit'] | str]
        | None
    ) = None
    defaultCompletionOptions: DefaultCompletionOptions | None = None
    cacheBehavior: CacheBehavior | None = None
    requestOptions: RequestOptions2 | None = None
    embedOptions: EmbedOptions | None = None
    chatOptions: ChatOptions1 | None = None
    promptTemplates: PromptTemplates1 | None = None
    useLegacyCompletionsEndpoint: bool | None = None
    useResponsesApi: bool | None = None
    env: dict[str, str | bool | float] | None = None
    autocompleteOptions: AutocompleteOptions | None = None
    provider: str
    sourceFile: str | None = None


class Uses(StrEnum):
    anthropic_claude_sonnet_4_6 = 'anthropic/claude-sonnet-4-6'
    anthropic_claude_opus_4_6 = 'anthropic/claude-opus-4-6'
    anthropic_claude_sonnet_4 = 'anthropic/claude-sonnet-4'
    togetherai_llama_4_maverick_instruct_17bx128e = (
        'togetherai/llama-4-maverick-instruct-17bx128e'
    )
    google_gemini_2_5_pro = 'google/gemini-2.5-pro'
    mistral_codestral = 'mistral/codestral'
    voyageai_voyage_code_3 = 'voyageai/voyage-code-3'
    anthropic_claude_sonnet_4_5 = 'anthropic/claude-sonnet-4-5'
    relace_instant_apply = 'relace/instant-apply'
    xai_grok_2 = 'xai/grok-2'
    openai_gpt_4o = 'openai/gpt-4o'
    togetherai_llama_4_scout_instruct_17bx16e = (
        'togetherai/llama-4-scout-instruct-17bx16e'
    )
    anthropic_claude_haiku_4_5 = 'anthropic/claude-haiku-4-5'
    google_gemini_2_5_flash = 'google/gemini-2.5-flash'
    voyageai_rerank_2 = 'voyageai/rerank-2'
    anthropic_claude_opus_4_1 = 'anthropic/claude-opus-4-1'
    ollama_deepseek_r1 = 'ollama/deepseek-r1'
    morphllm_morph_v0 = 'morphllm/morph-v0'
    lmstudio_deepseek_r1 = 'lmstudio/deepseek-r1'
    openai_o3_mini = 'openai/o3-mini'
    voyageai_voyage_code_2 = 'voyageai/voyage-code-2'
    ollama_qwen2_5_coder_1_5b = 'ollama/qwen2.5-coder-1.5b'
    openai_gpt_4o_mini = 'openai/gpt-4o-mini'
    openai_o1 = 'openai/o1'
    mistral_mistral_embed = 'mistral/mistral-embed'
    ollama_nomic_embed_text_latest = 'ollama/nomic-embed-text-latest'
    lmstudio_deepseek_r1_8b = 'lmstudio/deepseek-r1-8b'
    mistral_mistral_large = 'mistral/mistral-large'
    lmstudio_qwen2_5_coder_1_5b = 'lmstudio/qwen2.5-coder-1.5b'
    ollama_deepseek_r1_8b = 'ollama/deepseek-r1-8b'
    openai_text_embedding_3_large = 'openai/text-embedding-3-large'


class RequestOptions3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class ToolOverrides2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    displayTitle: str | None = None
    wouldLikeTo: str | None = None
    isCurrently: str | None = None
    hasAlready: str | None = None
    systemMessageDescription: SystemMessageDescription | None = None
    disabled: bool | None = None


class ChatOptions2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseSystemMessage: str | None = None
    baseAgentSystemMessage: str | None = None
    basePlanSystemMessage: str | None = None
    toolOverrides: dict[str, ToolOverrides2] | None = None


class PromptTemplates2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apply: str | None = None
    chat: Chat | None = None
    edit: str | None = None
    autocomplete: str | None = None


class Override(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    model: str | None = None
    apiKey: str | None = None
    apiBase: str | None = None
    contextLength: float | None = None
    maxStopWords: float | None = None
    roles: list[Role] | None = None
    capabilities: (
        list[Literal['tool_use'] | Literal['image_input'] | Literal['next_edit'] | str]
        | None
    ) = None
    defaultCompletionOptions: DefaultCompletionOptions | None = None
    cacheBehavior: CacheBehavior | None = None
    requestOptions: RequestOptions3 | None = None
    embedOptions: EmbedOptions | None = None
    chatOptions: ChatOptions2 | None = None
    promptTemplates: PromptTemplates2 | None = None
    useLegacyCompletionsEndpoint: bool | None = None
    useResponsesApi: bool | None = None
    env: dict[str, str | bool | float] | None = None
    autocompleteOptions: AutocompleteOptions | None = None
    provider: Literal['continue-proxy'] = 'continue-proxy'
    apiKeyLocation: str | None = None
    envSecretLocations: dict[str, str] | None = None


class RequestOptions4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class ToolOverrides3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    displayTitle: str | None = None
    wouldLikeTo: str | None = None
    isCurrently: str | None = None
    hasAlready: str | None = None
    systemMessageDescription: SystemMessageDescription | None = None
    disabled: bool | None = None


class ChatOptions3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseSystemMessage: str | None = None
    baseAgentSystemMessage: str | None = None
    basePlanSystemMessage: str | None = None
    toolOverrides: dict[str, ToolOverrides3] | None = None


class PromptTemplates3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apply: str | None = None
    chat: Chat | None = None
    edit: str | None = None
    autocomplete: str | None = None


class Override1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    model: str | None = None
    apiKey: str | None = None
    apiBase: str | None = None
    contextLength: float | None = None
    maxStopWords: float | None = None
    roles: list[Role] | None = None
    capabilities: (
        list[Literal['tool_use'] | Literal['image_input'] | Literal['next_edit'] | str]
        | None
    ) = None
    defaultCompletionOptions: DefaultCompletionOptions | None = None
    cacheBehavior: CacheBehavior | None = None
    requestOptions: RequestOptions4 | None = None
    embedOptions: EmbedOptions | None = None
    chatOptions: ChatOptions3 | None = None
    promptTemplates: PromptTemplates3 | None = None
    useLegacyCompletionsEndpoint: bool | None = None
    useResponsesApi: bool | None = None
    env: dict[str, str | bool | float] | None = None
    autocompleteOptions: AutocompleteOptions | None = None
    provider: str | None = None


class Models2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str | Uses
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override | Override1 | None = None


class Context(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    provider: str
    params: Any | None = None


class Override2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    provider: str | None = None
    params: Any | None = None


class Context1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override2 | None = None


class Level(StrEnum):
    all = 'all'
    noCode = 'noCode'


class RequestOptions5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    destination: str
    schema_: constr(
        pattern=r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'
    ) = Field(..., alias='schema')
    level: Level | None = None
    events: list[str] | None = None
    requestOptions: RequestOptions5 | None = None
    apiKey: str | None = None


class RequestOptions6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class Override3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    destination: str | None = None
    schema_: (
        constr(
            pattern=r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'
        )
        | None
    ) = Field(default=None, alias='schema')
    level: Level | None = None
    events: list[str] | None = None
    requestOptions: RequestOptions6 | None = None
    apiKey: str | None = None


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override3 | None = None


class McpServers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    serverName: str | None = None
    faviconUrl: str | None = None
    sourceFile: str | None = None
    sourceSlug: str | None = None
    connectionTimeout: PositiveFloat | None = None
    command: str
    type: Literal['stdio'] = 'stdio'
    args: list[str] | None = None
    env: dict[str, str] | None = None
    cwd: str | None = None


class Type(StrEnum):
    sse = 'sse'
    streamable_http = 'streamable-http'


class RequestOptions7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class McpServers1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    serverName: str | None = None
    faviconUrl: str | None = None
    sourceFile: str | None = None
    sourceSlug: str | None = None
    connectionTimeout: PositiveFloat | None = None
    url: str
    type: Type | None = None
    apiKey: str | None = None
    requestOptions: RequestOptions7 | None = None


class Override4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    serverName: str | None = None
    faviconUrl: str | None = None
    sourceFile: str | None = None
    sourceSlug: str | None = None
    connectionTimeout: PositiveFloat | None = None
    command: str | None = None
    type: Literal['stdio'] = 'stdio'
    args: list[str] | None = None
    env: dict[str, str] | None = None
    cwd: str | None = None


class RequestOptions8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timeout: float | None = None
    verifySsl: bool | None = None
    caBundlePath: str | list[str] | None = None
    proxy: str | None = None
    headers: dict[str, str] | None = None
    extraBodyProperties: dict[str, Any] | None = None
    noProxy: list[str] | None = None
    clientCertificate: ClientCertificate | None = None


class Override5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    serverName: str | None = None
    faviconUrl: str | None = None
    sourceFile: str | None = None
    sourceSlug: str | None = None
    connectionTimeout: PositiveFloat | None = None
    url: str | None = None
    type: Type | None = None
    apiKey: str | None = None
    requestOptions: RequestOptions8 | None = None


class McpServers2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override4 | Override5 | None = None


class Rules(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    rule: str
    description: str | None = None
    globs: str | list[str] | None = None
    regex: str | list[str] | None = None
    alwaysApply: bool | None = None
    invokable: bool | None = None
    sourceFile: str | None = None


class Rules1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')


class Prompts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    description: str | None = None
    prompt: str
    sourceFile: str | None = None


class Override6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    description: str | None = None
    prompt: str | None = None
    sourceFile: str | None = None


class Prompts1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override6 | None = None


class Docs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    startUrl: str
    rootUrl: str | None = None
    faviconUrl: str | None = None
    useLocalCrawling: bool | None = None
    sourceFile: str | None = None


class Override7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = None
    startUrl: str | None = None
    rootUrl: str | None = None
    faviconUrl: str | None = None
    useLocalCrawling: bool | None = None
    sourceFile: str | None = None


class Docs1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uses: str
    with_: dict[str, str] | None = Field(default=None, alias='with')
    override: Override7 | None = None


class ContinueConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    version: str
    schema_: str | None = Field(default=None, alias='schema')
    metadata: Metadata | None = None
    env: dict[str, str | float | bool] | None = None
    requestOptions: RequestOptions | None = None
    models: list[Models | Models1 | Models2] | None = None
    context: list[Context | Context1] | None = None
    data: list[Data | Data1] | None = None
    mcpServers: list[McpServers | McpServers1 | McpServers2] | None = None
    rules: list[str | Rules | Rules1] | None = None
    prompts: list[Prompts | Prompts1] | None = None
    docs: list[Docs | Docs1] | None = None


class Model(RootModel[ContinueConfig]):
    root: ContinueConfig
