# generated by datamodel-codegen:
#   filename:  mcpb-manifest.schema.json
#   timestamp: 2026-05-11T20:38:33+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel, constr


class Author(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    email: EmailStr | None = None
    url: AnyUrl | None = None


class Repository(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    url: AnyUrl


class Icon(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    src: str
    size: constr(pattern=r'^\d+x\d+$')
    theme: constr(min_length=1) | None = None


class Localization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resources: constr(pattern=r'\$\{locale\}')
    default_locale: constr(pattern=r'^[A-Za-z0-9]{2,8}(?:-[A-Za-z0-9]{1,8})*$')


class Type(StrEnum):
    python = 'python'
    node = 'node'
    binary = 'binary'
    uv = 'uv'


class Tool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    description: str | None = None


class Prompt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    description: str | None = None
    arguments: list[str] | None = None
    text: str


class Platform(StrEnum):
    darwin = 'darwin'
    win32 = 'win32'
    linux = 'linux'


class Runtimes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    python: str | None = None
    node: str | None = None


class Compatibility(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claude_desktop: str | None = None
    platforms: list[Platform] | None = None
    runtimes: Runtimes | None = None


class Type1(StrEnum):
    string = 'string'
    number = 'number'
    boolean = 'boolean'
    directory = 'directory'
    file = 'file'


class UserConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type1
    title: str
    description: str
    required: bool | None = None
    default: str | float | bool | list[str] | None = None
    multiple: bool | None = None
    sensitive: bool | None = None
    min: float | None = None
    max: float | None = None


class Args(RootModel[list[str]]):
    root: list[str]


class Command(RootModel[str]):
    root: str


class Env(RootModel[dict[str, str]]):
    root: dict[str, str]


class PlatformOverrides(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: Command | None = None
    args: Args | None = None
    env: Env | None = None


class McpConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: str
    args: list[str] | None = None
    env: dict[str, str] | None = None
    platform_overrides: dict[str, PlatformOverrides] | None = None


class Server(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    entry_point: str
    mcp_config: McpConfig


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str | None = Field(default=None, alias='$schema')
    dxt_version: Literal['0.4'] = '0.4'
    """
    @deprecated Use manifest_version instead
    """
    manifest_version: Literal['0.4'] = '0.4'
    name: str
    display_name: str | None = None
    version: str
    description: str
    long_description: str | None = None
    author: Author
    repository: Repository | None = None
    homepage: AnyUrl | None = None
    documentation: AnyUrl | None = None
    support: AnyUrl | None = None
    icon: str | None = None
    icons: list[Icon] | None = None
    screenshots: list[str] | None = None
    localization: Localization | None = None
    server: Server
    tools: list[Tool] | None = None
    tools_generated: bool | None = None
    prompts: list[Prompt] | None = None
    prompts_generated: bool | None = None
    keywords: list[str] | None = None
    license: str | None = None
    privacy_policies: list[AnyUrl] | None = None
    compatibility: Compatibility | None = None
    user_config: dict[str, UserConfig] | None = None
    field_meta: dict[str, dict[str, Any]] | None = Field(default=None, alias='_meta')
