#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the reporter inventory tables in the docs from the plugin registry.

Why this exists
---------------
The set of built-in reporters was stated in seven places -- the reporters package
``__all__``, ``ASH_REPORTERS`` in ``plugin_modules/ash_builtin/__init__.py``,
``ReporterConfigSegment`` in ``config/ash_config.py``, and four documentation
pages -- and no two of them agreed. Measured at the commit that introduced this
script: the registry had 15 reporters, ``ASH_REPORTERS`` listed 13,
``ReporterConfigSegment`` declared 14 fields, ``output-formats.md`` showed 14
rows, ``plugins/builtin/reporters.md`` claimed 14 in prose while tabulating 13,
``plugins/builtin/index.md`` said 13 and ``plugins/index.md`` said 12.

Reconciling six numbers by hand produces a seventh number that is correct for one
commit. Instead, the row set, the file extensions and the enabled-by-default
column are derived here from the registered reporter classes, which is the set a
scan actually runs, and written into marker-delimited regions of the docs.

What stays hand-written
-----------------------
The "primary use case" and "standard" columns are editorial and live in
``REPORTER_DOCS`` below, keyed by reporter name. They are deliberately NOT
derived: no attribute on a reporter class carries "what a reader would use this
for". The check is instead a completeness one -- a reporter registered with no
``REPORTER_DOCS`` entry, or an entry naming no registered reporter, is an error.
That way a newly added reporter cannot reach the docs as a blank row, and cannot
be silently omitted either.

Usage
-----
    uv run python scripts/generate_reporter_docs.py           # rewrite the docs
    uv run python scripts/generate_reporter_docs.py --check   # fail if stale

``--check`` is the freshness gate. It re-renders every region and compares
against what is on disk, exiting non-zero with a diff when they differ, so a
reporter added, removed, renamed, re-extensioned, or flipped between enabled and
disabled cannot land while the docs still describe the previous set.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BEGIN = "<!-- BEGIN GENERATED: {name} -->"
END = "<!-- END GENERATED: {name} -->"
REGEN_NOTE = (
    "<!-- Generated by scripts/generate_reporter_docs.py from the registered "
    "reporter set. Do not edit between the markers; run "
    "`uv run python scripts/generate_reporter_docs.py` instead. -->"
)

# Editorial metadata per reporter name. `anchor` is the in-page anchor for
# output-formats.md when that page carries a detail section for the format, or
# None when it does not (the row then renders as plain text, matching how the
# page already treated gitlab-cyclonedx and github-ghas).
REPORTER_DOCS: dict[str, dict] = {
    "csv": {
        "title": "CSV",
        "anchor": "csv",
        "use_case": "Spreadsheet analysis, filtering",
        "standard": "RFC 4180",
        "plugin_format": "CSV",
        "plugin_use_case": "Data analysis, spreadsheets",
        "plugin_features": "Tabular data, easy filtering",
    },
    "cyclonedx": {
        "title": "CycloneDX",
        "anchor": "cyclonedx",
        "use_case": "Software bill of materials (SBOM)",
        "standard": "[CycloneDX 1.6](https://cyclonedx.org/specification/overview/)",
        "plugin_format": "JSON/XML",
        "plugin_use_case": "SBOM compliance",
        "plugin_features": "Software Bill of Materials",
    },
    "flat-json": {
        "title": "Flat JSON",
        "anchor": "flat-json",
        "use_case": "Programmatic consumption, dashboards",
        "standard": "ASH-native",
        "plugin_format": "JSON",
        "plugin_use_case": "Simple data processing",
        "plugin_features": "Flattened structure",
    },
    "github-ghas": {
        "title": "GitHub GHAS",
        "anchor": None,
        "use_case": "GitHub Advanced Security code scanning upload",
        "standard": "[OASIS SARIF 2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html)",
        "plugin_format": "SARIF",
        "plugin_use_case": "GitHub Advanced Security",
        "plugin_features": "Optimized SARIF with proper severity mapping",
    },
    "gitlab-cyclonedx": {
        "title": "GitLab CycloneDX",
        "anchor": None,
        "use_case": "GitLab dependency scanning",
        "standard": "[GitLab dependency scanning report](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportsdependency_scanning)",
        "plugin_format": "JSON",
        "plugin_use_case": "GitLab dependency scanning",
        "plugin_features": "CycloneDX SBOM in GitLab's report format",
    },
    "gitlab-sast": {
        "title": "GitLab SAST",
        "anchor": "gitlab-sast",
        "use_case": "GitLab Security Dashboard",
        "standard": "[GitLab SAST report](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportssast)",
        "plugin_format": "JSON",
        "plugin_use_case": "GitLab Security Dashboard",
        "plugin_features": "GitLab CI/CD integration",
    },
    "html": {
        "title": "HTML",
        "anchor": "html",
        "use_case": "Interactive browser-based reports",
        "standard": "--",
        "plugin_format": "HTML",
        "plugin_use_case": "Interactive reports",
        "plugin_features": "Web-based, searchable",
    },
    "junitxml": {
        "title": "JUnit XML",
        "anchor": "junit-xml",
        "use_case": "CI/CD test result reporting",
        "standard": "[JUnit XML](https://llg.cubic.org/docs/junit/)",
        "plugin_format": "XML",
        "plugin_use_case": "CI/CD test results",
        "plugin_features": "Test framework integration",
    },
    "markdown": {
        "title": "Markdown",
        "anchor": "markdown",
        "use_case": "Pull request comments, documentation",
        "standard": "CommonMark",
        "plugin_format": "Markdown",
        "plugin_use_case": "Documentation, README",
        "plugin_features": "Human-readable, version control friendly",
    },
    "ocsf": {
        "title": "OCSF",
        "anchor": "ocsf",
        "use_case": "Security data lakes, SIEM ingestion",
        "standard": "[OCSF 1.0](https://schema.ocsf.io/)",
        "plugin_format": "JSON",
        "plugin_use_case": "Security data lakes",
        "plugin_features": "Open Cybersecurity Schema Framework",
    },
    "sarif": {
        "title": "SARIF",
        "anchor": "sarif",
        "use_case": "IDE integration, GitHub/GitLab code scanning",
        "standard": "[OASIS SARIF 2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html)",
        "plugin_format": "JSON",
        "plugin_use_case": "IDE integration, CI/CD",
        "plugin_features": "Static Analysis Results Interchange Format",
    },
    "spdx": {
        "title": "SPDX",
        "anchor": "spdx",
        "use_case": "License compliance, SBOM",
        "standard": "[SPDX 2.3](https://spdx.dev/specifications/)",
        "plugin_format": "JSON",
        "plugin_use_case": "License compliance",
        "plugin_features": "Software Package Data Exchange",
    },
    "text": {
        "title": "Text",
        "anchor": "text",
        "use_case": "Console output, logs",
        "standard": "--",
        "plugin_format": "Plain text",
        "plugin_use_case": "Console output, logs",
        "plugin_features": "Simple, lightweight",
    },
    "unused-suppressions": {
        "title": "Unused suppressions",
        "anchor": None,
        "use_case": "Suppression hygiene: rules that matched nothing this scan",
        "standard": "ASH-native",
        "plugin_format": "JSON",
        "plugin_use_case": "Suppression hygiene",
        "plugin_features": "Lists configured suppressions that matched no finding",
    },
    "yaml": {
        "title": "YAML",
        "anchor": "yaml",
        "use_case": "Human-readable structured data",
        "standard": "--",
        "plugin_format": "YAML",
        "plugin_use_case": "Configuration-style output",
        "plugin_features": "Human-readable structured data",
    },
}


def registered_reporters() -> list[dict]:
    """Return {name, extension, enabled, class_name} for every registered reporter.

    Importing the reporters package fires the ``@ash_reporter_plugin``
    decorators, so the plugin manager's reporter inventory after this import is
    the set a scan would run. Each reporter's defaults come from instantiating
    its config class with no arguments, which is exactly what ASH does when a
    user names no reporter options.
    """
    import automated_security_helper.plugin_modules.ash_builtin.reporters  # noqa: F401
    from automated_security_helper.plugins import ash_plugin_manager

    import typing

    rows = []
    for cls in ash_plugin_manager.plugin_modules("reporter"):
        field = getattr(cls, "model_fields", {}).get("config")
        if field is None:
            raise RuntimeError(f"{cls.__name__} has no `config` model field")
        annotation = field.annotation
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        config_cls = args[0] if args else annotation
        config = config_cls()
        rows.append(
            {
                "name": config.name,
                "extension": getattr(config, "extension", None),
                "enabled": bool(config.enabled),
                "class_name": cls.__name__,
            }
        )
    rows.sort(key=lambda r: r["name"])
    return rows


def _check_editorial_coverage(rows: list[dict]) -> None:
    registered = {r["name"] for r in rows}
    documented = set(REPORTER_DOCS)
    missing = sorted(registered - documented)
    extra = sorted(documented - registered)
    problems = []
    if missing:
        problems.append(
            f"registered reporters with no REPORTER_DOCS entry: {missing}. "
            f"Add a use case and standard for each in scripts/generate_reporter_docs.py."
        )
    if extra:
        problems.append(
            f"REPORTER_DOCS entries naming no registered reporter: {extra}. "
            f"Remove them, or fix the reporter's registration."
        )
    if problems:
        raise SystemExit("ERROR: " + "\n       ".join(problems))


def _prose_list(names: list[str]) -> str:
    """Render names as `a`, `b`, and `c`."""
    ticked = [f"`{n}`" for n in names]
    if len(ticked) == 1:
        return ticked[0]
    if len(ticked) == 2:
        return f"{ticked[0]} and {ticked[1]}"
    return ", ".join(ticked[:-1]) + f", and {ticked[-1]}"


# --------------------------------------------------------------------------
# Region renderers. Each returns the body that goes between its markers.
# --------------------------------------------------------------------------


def render_output_formats_table(rows: list[dict]) -> str:
    lines = [
        "| Format | File extension | Enabled by default | Primary use case | Standard |",
        "|--------|---------------|--------------------|-----------------|----------|",
    ]
    for r in rows:
        doc = REPORTER_DOCS[r["name"]]
        anchor = doc["anchor"]
        label = (
            f"[{doc['title']}](#{anchor}) (`{r['name']}`)"
            if anchor
            else f"{doc['title']} (`{r['name']}`)"
        )
        enabled = "Yes" if r["enabled"] else "No"
        lines.append(
            f"| {label} | `.{r['extension']}` | {enabled} | {doc['use_case']} | {doc['standard']} |"
        )
    return "\n".join(lines)


def render_output_formats_defaults(rows: list[dict]) -> str:
    on = [r["name"] for r in rows if r["enabled"]]
    off = [r["name"] for r in rows if not r["enabled"]]
    sentence = (
        f"Of the {len(rows)} built-in reporters, {len(on)} are enabled by default: "
        f"{_prose_list(on)}."
    )
    if off:
        sentence += (
            f" {_prose_list(off)} "
            f"{'is' if len(off) == 1 else 'are'} available but disabled by default."
        )
    return sentence


def render_plugin_reporters_table(rows: list[dict]) -> str:
    lines = [
        "| Reporter | Name | Format | Enabled by default | Use Case | Key Features |",
        "|----------|------|--------|--------------------|----------|--------------|",
    ]
    for r in rows:
        doc = REPORTER_DOCS[r["name"]]
        slug = doc["title"].lower().replace(" ", "-")
        enabled = "Yes" if r["enabled"] else "No"
        lines.append(
            f"| **[{doc['title']} Reporter](#{slug}-reporter)** | `{r['name']}` | "
            f"{doc['plugin_format']} | {enabled} | {doc['plugin_use_case']} | "
            f"{doc['plugin_features']} |"
        )
    return "\n".join(lines)


def render_plugin_reporters_count(rows: list[dict]) -> str:
    return (
        f"ASH includes {len(rows)} built-in reporters that generate scan results in "
        f"various formats to support different use cases, from human-readable reports "
        f"to machine-processable data formats for CI/CD integration."
    )


def render_builtin_index_counts(rows: list[dict]) -> str:
    import automated_security_helper.plugin_modules.ash_builtin as builtin

    counts = {
        "scanners": len(builtin.ASH_SCANNERS),
        "reporters": len(rows),
        "converters": len(builtin.ASH_CONVERTERS),
        "event_handlers": sum(len(v) for v in builtin.ASH_EVENT_HANDLERS.values()),
    }
    return "\n".join(
        [
            "| Category | Purpose | Count | Location |",
            "|----------|---------|-------|----------|",
            (
                f"| **[Scanners](scanners.md)** | Analyze code and infrastructure for "
                f"security vulnerabilities | {counts['scanners']} | `scanners/` |"
            ),
            (
                f"| **[Reporters](reporters.md)** | Generate scan results in various "
                f"output formats | {counts['reporters']} | `reporters/` |"
            ),
            (
                f"| **[Converters](converters.md)** | Process and prepare files for "
                f"scanning | {counts['converters']} | `converters/` |"
            ),
            (
                f"| **[Event Handlers](event-handlers.md)** | Handle scan lifecycle "
                f"events and notifications | {counts['event_handlers']} | `event_handlers/` |"
            ),
        ]
    )


def render_plugins_index_bullet(rows: list[dict]) -> str:
    return (
        f"- **[Report Formats](./builtin/reporters.md)**: {len(rows)} output formats "
        f"(SARIF, HTML, CSV, etc.)"
    )


REGIONS: list[tuple[str, str, object]] = [
    (
        "docs/content/docs/output-formats.md",
        "reporter-quick-reference",
        render_output_formats_table,
    ),
    (
        "docs/content/docs/output-formats.md",
        "reporter-defaults",
        render_output_formats_defaults,
    ),
    (
        "docs/content/docs/plugins/builtin/reporters.md",
        "reporter-count",
        render_plugin_reporters_count,
    ),
    (
        "docs/content/docs/plugins/builtin/reporters.md",
        "reporter-overview",
        render_plugin_reporters_table,
    ),
    (
        "docs/content/docs/plugins/builtin/index.md",
        "builtin-plugin-counts",
        render_builtin_index_counts,
    ),
    (
        "docs/content/docs/plugins/index.md",
        "reporter-format-count",
        render_plugins_index_bullet,
    ),
]


def _region_pattern(name: str) -> re.Pattern:
    # `(?:.*?\n)?` rather than `.*?\n` so that an empty region -- BEGIN
    # immediately followed by END, which is how a region is first introduced into
    # a page -- still matches and gets populated.
    return re.compile(
        re.escape(BEGIN.format(name=name))
        + r"\n(?:.*?\n)?"
        + re.escape(END.format(name=name)),
        re.DOTALL,
    )


def _replacement(name: str, body: str) -> str:
    return "\n".join([BEGIN.format(name=name), REGEN_NOTE, body, END.format(name=name)])


def apply_regions(check: bool) -> int:
    rows = registered_reporters()
    _check_editorial_coverage(rows)

    stale = []
    for rel_path, name, renderer in REGIONS:
        path = REPO_ROOT / rel_path
        original = path.read_text(encoding="utf-8")
        pattern = _region_pattern(name)
        if not pattern.search(original):
            raise SystemExit(
                f"ERROR: {rel_path} has no '{name}' generated region. Expected the "
                f"markers {BEGIN.format(name=name)} ... {END.format(name=name)}."
            )
        # A function replacement is used verbatim by re.sub -- no backslash or
        # group-reference escaping is applied to it. That matters because the
        # rendered tables contain URLs and backslashes would otherwise need
        # escaping here and unescaping on read.
        rendered = _replacement(name, renderer(rows))
        updated = pattern.sub(lambda _m: rendered, original, count=1)
        if updated == original:
            continue
        if check:
            stale.append((rel_path, name, original, updated))
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"updated {rel_path} [{name}]", file=sys.stderr)

    if check and stale:
        print(
            "Reporter documentation is stale relative to the registered reporter set.\n"
            "Run: uv run python scripts/generate_reporter_docs.py\n",
            file=sys.stderr,
        )
        for rel_path, name, original, updated in stale:
            diff = difflib.unified_diff(
                original.splitlines(keepends=True),
                updated.splitlines(keepends=True),
                fromfile=f"{rel_path} (on disk)",
                tofile=f"{rel_path} (regenerated)",
                n=1,
            )
            print(f"--- region {name} ---", file=sys.stderr)
            sys.stderr.writelines(diff)
        return 1

    if check:
        print(
            f"Reporter documentation is up to date "
            f"({len(rows)} registered reporters, "
            f"{sum(1 for r in rows if r['enabled'])} enabled by default).",
            file=sys.stderr,
        )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write. Exit non-zero with a diff if any region is stale.",
    )
    args = parser.parse_args()
    return apply_regions(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
