# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate synthetic test data docx for ferret-scan plugin testing.

This script creates a docx file with synthetic PII-like data covering
all ferret-scan check categories. All data is entirely fictional and
generated programmatically — no real PII is used.

Usage:
    uv run python scripts/generate_test_docx.py
"""

import random
import string
from pathlib import Path

from docx import Document
from docx.shared import Pt

OUTPUT_PATH = Path("tests/test_data/scanners/ferret-scan/synthetic-pii-test.docx")

# Seed for reproducibility
random.seed(42)

# ============================================================================
# Synthetic data generators
# ============================================================================

FIRST_NAMES = [
    "Alice", "Bob", "Carol", "David", "Eve", "Frank", "Grace", "Henry",
    "Iris", "Jack", "Karen", "Leo", "Mia", "Noah", "Olivia", "Paul",
    "Quinn", "Rosa", "Sam", "Tina", "Uma", "Victor", "Wendy", "Xavier",
    "Yara", "Zane",
]

LAST_NAMES = [
    "Anderson", "Brown", "Clark", "Davis", "Evans", "Foster", "Garcia",
    "Harris", "Ingram", "Johnson", "King", "Lopez", "Miller", "Nelson",
    "Ortiz", "Parker", "Quinn", "Roberts", "Smith", "Taylor", "Underwood",
    "Vance", "Williams", "Xu", "Young", "Zhang",
]


def fake_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"


def fake_ssn():
    """Generate a fake SSN (uses 900-999 area numbers which are not assigned)."""
    area = random.randint(900, 999)
    group = random.randint(10, 99)
    serial = random.randint(1000, 9999)
    return f"{area}-{group}-{serial}"


def fake_visa():
    """Generate a fake Visa-like number (starts with 4, random digits)."""
    digits = "4" + "".join(str(random.randint(0, 9)) for _ in range(15))
    return f"{digits[0:4]}-{digits[4:8]}-{digits[8:12]}-{digits[12:16]}"


def fake_mastercard():
    """Generate a fake MasterCard-like number (starts with 5)."""
    digits = "5" + str(random.randint(1, 5)) + "".join(str(random.randint(0, 9)) for _ in range(14))
    return f"{digits[0:4]}-{digits[4:8]}-{digits[8:12]}-{digits[12:16]}"


def fake_amex():
    """Generate a fake AMEX-like number (starts with 37)."""
    digits = "37" + "".join(str(random.randint(0, 9)) for _ in range(13))
    return f"{digits[0:4]}-{digits[4:10]}-{digits[10:15]}"


def fake_discover():
    """Generate a fake Discover-like number (starts with 6011, random digits)."""
    digits = "6011" + "".join(str(random.randint(0, 9)) for _ in range(12))
    return f"{digits[0:4]} {digits[4:8]} {digits[8:12]} {digits[12:16]}"


def fake_email(name):
    first, last = name.lower().split()
    domains = ["example.com", "test.org", "sample.net", "demo.io"]
    return f"{first}.{last}@{random.choice(domains)}"


def fake_phone():
    area = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line = random.randint(1000, 9999)
    return f"({area}) {prefix}-{line}"


def fake_passport():
    letter = random.choice(string.ascii_uppercase)
    digits = "".join(str(random.randint(0, 9)) for _ in range(8))
    return f"{letter}{digits}"


def main():
    doc = Document()

    # Clear default metadata
    core = doc.core_properties
    core.author = "ASH Test Data Generator"
    core.title = "Synthetic PII Test Data for Ferret-Scan"
    core.subject = "Test data - all PII is fictional"
    core.comments = (
        "Generated by automated_security_helper for plugin testing. "
        "All data is synthetic. No real PII. Apache-2.0 licensed."
    )

    # Title
    title = doc.add_heading("Synthetic PII Test Data", level=1)
    doc.add_paragraph(
        "This document contains synthetic (fake) PII data for testing "
        "ferret-scan's detection capabilities. All data is entirely fictional "
        "and generated programmatically. No real personal information is included."
    )
    doc.add_paragraph(
        "Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. "
        "SPDX-License-Identifier: Apache-2.0"
    )

    # ---- Section 1: Plain text PII that matches ferret-scan patterns ----
    # These use the same formats that work in sample.txt
    doc.add_heading("Section 1: Credit Card Numbers", level=2)

    # Generate card numbers programmatically to avoid hardcoded strings
    # that trigger secret detectors in CI (which runs --ignore-suppressions)
    for _ in range(5):
        doc.add_paragraph(f"Visa: {fake_visa()}")

    for _ in range(5):
        doc.add_paragraph(f"MasterCard: {fake_mastercard()}")

    for _ in range(3):
        doc.add_paragraph(f"American Express: {fake_amex()}")

    for _ in range(2):
        doc.add_paragraph(f"Discover: {fake_discover()}")

    doc.add_heading("Section 2: Social Security Numbers", level=2)
    for _ in range(5):
        doc.add_paragraph(f"SSN: {fake_ssn()}")

    doc.add_heading("Section 3: Passport Numbers", level=2)
    for _ in range(5):
        doc.add_paragraph(f"Passport: {fake_passport()}")
    # MRZ-style lines
    doc.add_paragraph("Passport: P<USASMITH<<JOHN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    doc.add_paragraph("Passport: P<GBRJONES<<SARAH<<<<<<<<<<<<<<<<<<<<<<<<<<<<")

    doc.add_heading("Section 4: Phone Numbers", level=2)
    for _ in range(5):
        doc.add_paragraph(f"Phone: {fake_phone()}")

    doc.add_heading("Section 5: Contact Records", level=2)

    # Free-text narratives with embedded PII (generated to avoid hardcoded secrets)
    narratives = [
        f"Customer {fake_name()} (SSN: {fake_ssn()}) reported unauthorized charges "
        f"on Visa card {fake_visa()}. Contact at {fake_phone()}.",

        f"Employee {fake_name()} submitted expense report. Corporate MasterCard "
        f"{fake_mastercard()} used for travel. Phone: {fake_phone()}.",

        f"Account holder {fake_name()} requested replacement AMEX card {fake_amex()}. "
        f"Verified identity with SSN {fake_ssn()} and passport {fake_passport()}.",

        f"HR record for {fake_name()}: SSN {fake_ssn()}, phone {fake_phone()}. "
        f"Travel document: passport {fake_passport()}. Company Visa: {fake_visa()}.",

        f"Please charge Visa card {fake_visa()} for the full amount. "
        f"The MasterCard ending in 3020 ({fake_mastercard()}) has been approved.",

        f"AMEX: {fake_amex()} - Expiration: 12/25. "
        f"Discover card {fake_discover()} authorized for recurring payments.",
    ]
    for n in narratives:
        doc.add_paragraph(n)

    # ---- Section 6: Bulk records to add volume ----
    doc.add_heading("Section 6: Extended Records", level=2)

    NUM_RECORDS = 200

    for _ in range(NUM_RECORDS):
        name = fake_name()
        doc.add_paragraph(
            f"{name} | {fake_ssn()} | {fake_visa()} | {fake_mastercard()} | "
            f"{fake_amex()} | {fake_email(name)} | {fake_phone()} | {fake_passport()}"
        )

    # Save
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(OUTPUT_PATH))
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"Generated: {OUTPUT_PATH} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
