# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate synthetic test data docx for ferret-scan plugin testing.

This script creates a docx file with synthetic PII-like data covering
all ferret-scan check categories. All data is entirely fictional and
generated programmatically — no real PII is used.

Usage:
    uv run python scripts/generate_test_docx.py
"""

import random
import string
from pathlib import Path

from docx import Document
from docx.shared import Pt

OUTPUT_PATH = Path("tests/test_data/scanners/ferret-scan/synthetic-pii-test.docx")

# Seed for reproducibility
random.seed(42)

# ============================================================================
# Synthetic data generators
# ============================================================================

FIRST_NAMES = [
    "Alice", "Bob", "Carol", "David", "Eve", "Frank", "Grace", "Henry",
    "Iris", "Jack", "Karen", "Leo", "Mia", "Noah", "Olivia", "Paul",
    "Quinn", "Rosa", "Sam", "Tina", "Uma", "Victor", "Wendy", "Xavier",
    "Yara", "Zane",
]

LAST_NAMES = [
    "Anderson", "Brown", "Clark", "Davis", "Evans", "Foster", "Garcia",
    "Harris", "Ingram", "Johnson", "King", "Lopez", "Miller", "Nelson",
    "Ortiz", "Parker", "Quinn", "Roberts", "Smith", "Taylor", "Underwood",
    "Vance", "Williams", "Xu", "Young", "Zhang",
]


def fake_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"


def fake_ssn():
    """Generate a fake SSN (uses 900-999 area numbers which are not assigned)."""
    area = random.randint(900, 999)
    group = random.randint(10, 99)
    serial = random.randint(1000, 9999)
    return f"{area}-{group}-{serial}"


def fake_visa():
    """Generate a fake Visa-like number (starts with 4, random digits)."""
    digits = "4" + "".join(str(random.randint(0, 9)) for _ in range(15))
    return f"{digits[0:4]}-{digits[4:8]}-{digits[8:12]}-{digits[12:16]}"


def fake_mastercard():
    """Generate a fake MasterCard-like number (starts with 5)."""
    digits = "5" + str(random.randint(1, 5)) + "".join(str(random.randint(0, 9)) for _ in range(14))
    return f"{digits[0:4]}-{digits[4:8]}-{digits[8:12]}-{digits[12:16]}"


def fake_amex():
    """Generate a fake AMEX-like number (starts with 37)."""
    digits = "37" + "".join(str(random.randint(0, 9)) for _ in range(13))
    return f"{digits[0:4]}-{digits[4:10]}-{digits[10:15]}"


def fake_email(name):
    first, last = name.lower().split()
    domains = ["example.com", "test.org", "sample.net", "demo.io"]
    return f"{first}.{last}@{random.choice(domains)}"


def fake_phone():
    area = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line = random.randint(1000, 9999)
    return f"({area}) {prefix}-{line}"


def fake_passport():
    letter = random.choice(string.ascii_uppercase)
    digits = "".join(str(random.randint(0, 9)) for _ in range(8))
    return f"{letter}{digits}"


def main():
    doc = Document()

    # Clear default metadata
    core = doc.core_properties
    core.author = "ASH Test Data Generator"
    core.title = "Synthetic PII Test Data for Ferret-Scan"
    core.subject = "Test data - all PII is fictional"
    core.comments = (
        "Generated by automated_security_helper for plugin testing. "
        "All data is synthetic. No real PII. Apache-2.0 licensed."
    )

    # Title
    title = doc.add_heading("Synthetic PII Test Data", level=1)
    doc.add_paragraph(
        "This document contains synthetic (fake) PII data for testing "
        "ferret-scan's detection capabilities. All data is entirely fictional "
        "and generated programmatically. No real personal information is included."
    )
    doc.add_paragraph(
        "Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. "
        "SPDX-License-Identifier: Apache-2.0"
    )

    # ---- Section 1: Plain text PII that matches ferret-scan patterns ----
    # These use the same formats that work in sample.txt
    doc.add_heading("Section 1: Credit Card Numbers", level=2)

    # Visa cards (start with 4, 16 digits, space-separated groups)
    visa_numbers = [
        "4532 0151 9562 0486",
        "4539 7469 3419 6337",
        "4916 4811 5814 8111",
        "4916 4034 9269 8783",
        "4929 3813 3266 4295",
    ]
    for v in visa_numbers:
        doc.add_paragraph(f"Visa: {v}")

    # MasterCard (start with 5, 16 digits)
    mc_numbers = [
        "5425 2334 3010 9903",
        "5370 4638 8881 3020",
        "5299 1561 5689 1938",
        "5293 8502 0071 3058",
        "5548 0246 6336 5664",
    ]
    for m in mc_numbers:
        doc.add_paragraph(f"MasterCard: {m}")

    # AMEX (start with 37, 15 digits)
    amex_numbers = [
        "3714 496353 98431",
        "3782 822463 10005",
        "3787 344936 71000",
    ]
    for a in amex_numbers:
        doc.add_paragraph(f"American Express: {a}")

    # Discover (start with 6011)
    discover_numbers = [
        "6011 6011 6011 6611",
        "6011 0009 9013 9424",
    ]
    for d in discover_numbers:
        doc.add_paragraph(f"Discover: {d}")

    doc.add_heading("Section 2: Social Security Numbers", level=2)
    ssn_examples = [
        "489-36-8350",
        "514-14-8905",
        "690-05-5315",
        "421-37-1396",
        "458-02-6124",
    ]
    for s in ssn_examples:
        doc.add_paragraph(f"SSN: {s}")

    doc.add_heading("Section 3: Passport Numbers", level=2)
    passport_examples = [
        "C01234567",
        "AB123456",
        "DE1234567",
        "P<USASMITH<<JOHN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<",
        "P<GBRJONES<<SARAH<<<<<<<<<<<<<<<<<<<<<<<<<<<<",
    ]
    for p in passport_examples:
        doc.add_paragraph(f"Passport: {p}")

    doc.add_heading("Section 4: Phone Numbers", level=2)
    phone_examples = [
        "(555) 123-4567",
        "(800) 555-0199",
        "+1 (212) 555-0100",
        "1-800-555-0123",
        "(415) 555-2671",
    ]
    for ph in phone_examples:
        doc.add_paragraph(f"Phone: {ph}")

    doc.add_heading("Section 5: Contact Records", level=2)

    # Free-text narratives with embedded PII (same style as sample.txt)
    narratives = [
        "Customer Robert Anderson (SSN: 489-36-8350) reported unauthorized charges "
        "on Visa card 4532 0151 9562 0486. Contact at (555) 123-4567.",

        "Employee Ashley Brown submitted expense report. Corporate MasterCard "
        "5425 2334 3010 9903 used for travel. Phone: (800) 555-0199.",

        "Account holder Thomas Clark requested replacement AMEX card 3714 496353 98431. "
        "Verified identity with SSN 514-14-8905 and passport C01234567.",

        "HR record for Susan Davis: SSN 690-05-5315, phone (415) 555-2671. "
        "Travel document: passport AB123456. Company Visa: 4539 7469 3419 6337.",

        "Please charge Visa card 4916 4811 5814 8111 for the full amount. "
        "The MasterCard ending in 3020 (5370 4638 8881 3020) has been approved.",

        "AMEX: 3782 822463 10005 - Expiration: 12/25. "
        "Discover card 6011 0009 9013 9424 authorized for recurring payments.",
    ]
    for n in narratives:
        doc.add_paragraph(n)

    # ---- Section 6: Bulk records to add volume ----
    doc.add_heading("Section 6: Extended Records", level=2)

    NUM_RECORDS = 200

    for _ in range(NUM_RECORDS):
        name = fake_name()
        doc.add_paragraph(
            f"{name} | {fake_ssn()} | {fake_visa()} | {fake_mastercard()} | "
            f"{fake_amex()} | {fake_email(name)} | {fake_phone()} | {fake_passport()}"
        )

    # Save
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(OUTPUT_PATH))
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"Generated: {OUTPUT_PATH} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
