# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tests for the markdown reporter compact mode."""

import pytest
from unittest.mock import MagicMock, patch

from automated_security_helper.models.asharp_model import AshAggregatedResults
from automated_security_helper.plugin_modules.ash_builtin.reporters.markdown_reporter import (
    MarkdownReporter,
    MarkdownReporterConfig,
    MarkdownReporterConfigOptions,
)


def _make_scanner_metric(
    name: str,
    status: str,
    total: int = 0,
    critical: int = 0,
    high: int = 0,
    medium: int = 0,
    low: int = 0,
    info: int = 0,
    suppressed: int = 0,
    actionable: int = 0,
):
    """Build a mock scanner metric object."""
    m = MagicMock()
    m.scanner_name = name
    m.status = status
    m.total = total
    m.critical = critical
    m.high = high
    m.medium = medium
    m.low = low
    m.info = info
    m.suppressed = suppressed
    m.actionable = actionable
    m.passed = status == "PASSED"
    m.threshold = "MEDIUM"
    m.threshold_source = "global"
    m.excluded = False
    m.dependencies_missing = False
    return m


class TestMarkdownCompactMode:
    """Tests for the compact option on the markdown reporter."""

    def _render(self, model, context, compact=False, **extra_opts):
        """Helper to render a report with the given compact setting."""
        opts = MarkdownReporterConfigOptions(compact=compact, **extra_opts)
        config = MarkdownReporterConfig(options=opts)
        reporter = MarkdownReporter(config=config, context=context)
        return reporter.report(model)

    # ------------------------------------------------------------------
    # Fixtures
    # ------------------------------------------------------------------

    @pytest.fixture
    def model_with_scanners(self):
        """Build a minimal AshAggregatedResults."""
        from automated_security_helper.config.default_config import get_default_config
        from automated_security_helper.config.ash_config import AshConfig

        AshConfig.model_rebuild()
        AshAggregatedResults.model_rebuild()

        model = AshAggregatedResults()
        model.metadata.scanner_name = "test"
        model.metadata.scan_id = "test-id"
        model.ash_config = get_default_config()
        return model

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------

    def test_compact_false_includes_metadata_section(
        self, model_with_scanners, test_plugin_context
    ):
        """Default (non-compact) output contains the Scan Metadata section."""
        output = self._render(model_with_scanners, test_plugin_context, compact=False)
        assert "## Scan Metadata" in output

    def test_compact_true_omits_metadata_section(
        self, model_with_scanners, test_plugin_context
    ):
        """Compact output omits the Scan Metadata section."""
        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "## Scan Metadata" not in output

    def test_compact_true_omits_footer(
        self, model_with_scanners, test_plugin_context
    ):
        """Compact output omits the ASH footer link."""
        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "Report generated by" not in output
        assert "automated-security-helper" not in output

    def test_compact_false_includes_footer(
        self, model_with_scanners, test_plugin_context
    ):
        """Default output includes the ASH footer link."""
        output = self._render(model_with_scanners, test_plugin_context, compact=False)
        assert "Report generated by" in output

    def test_compact_true_omits_severity_legend(
        self, model_with_scanners, test_plugin_context
    ):
        """Compact output omits the verbose severity legend block."""
        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "Severity levels" not in output
        assert "Statistics calculation" not in output

    def test_compact_false_includes_severity_legend(
        self, model_with_scanners, test_plugin_context
    ):
        """Default output includes the severity legend."""
        output = self._render(model_with_scanners, test_plugin_context, compact=False)
        assert "Severity levels" in output

    @patch(
        "automated_security_helper.plugin_modules.ash_builtin.reporters.report_content_emitter.get_unified_scanner_metrics"
    )
    def test_compact_skips_skipped_scanner_rows(
        self, mock_metrics, model_with_scanners, test_plugin_context
    ):
        """Compact mode omits rows where the scanner status is SKIPPED."""
        mock_metrics.return_value = [
            _make_scanner_metric("semgrep", "FAILED", total=3, high=2, actionable=2),
            _make_scanner_metric("bandit", "SKIPPED"),
        ]

        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "semgrep" in output
        assert "bandit" not in output

    @patch(
        "automated_security_helper.plugin_modules.ash_builtin.reporters.report_content_emitter.get_unified_scanner_metrics"
    )
    def test_compact_skips_zero_finding_passed_rows(
        self, mock_metrics, model_with_scanners, test_plugin_context
    ):
        """Compact mode omits rows where total == 0 and status is PASSED."""
        mock_metrics.return_value = [
            _make_scanner_metric("semgrep", "FAILED", total=1, medium=1, actionable=1),
            _make_scanner_metric("checkov", "PASSED", total=0),
        ]

        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "semgrep" in output
        assert "checkov" not in output

    @patch(
        "automated_security_helper.plugin_modules.ash_builtin.reporters.report_content_emitter.get_unified_scanner_metrics"
    )
    def test_non_compact_keeps_all_scanner_rows(
        self, mock_metrics, model_with_scanners, test_plugin_context
    ):
        """Non-compact mode keeps SKIPPED and zero-finding rows."""
        mock_metrics.return_value = [
            _make_scanner_metric("semgrep", "FAILED", total=1, medium=1, actionable=1),
            _make_scanner_metric("bandit", "SKIPPED"),
            _make_scanner_metric("checkov", "PASSED", total=0),
        ]

        output = self._render(model_with_scanners, test_plugin_context, compact=False)
        assert "semgrep" in output
        assert "bandit" in output
        assert "checkov" in output

    def test_compact_still_has_header_and_summary_table(
        self, model_with_scanners, test_plugin_context
    ):
        """Compact mode still emits the report header and the summary table."""
        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "# ASH Security Scan Report" in output
        assert "## Summary" in output
        assert "### Scanner Results" in output

    @patch(
        "automated_security_helper.plugin_modules.ash_builtin.reporters.report_content_emitter.get_unified_scanner_metrics"
    )
    def test_compact_all_scanners_filtered_produces_valid_output(
        self, mock_metrics, model_with_scanners, test_plugin_context
    ):
        """When all scanners are SKIPPED or zero-finding in compact mode, output is still valid markdown."""
        mock_metrics.return_value = [
            _make_scanner_metric("bandit", "SKIPPED"),
            _make_scanner_metric("checkov", "PASSED", total=0),
        ]

        output = self._render(model_with_scanners, test_plugin_context, compact=True)
        assert "### Scanner Results" in output
        assert "bandit" not in output
        assert "checkov" not in output

    def test_compact_option_defaults_to_false(self):
        """The compact option defaults to False."""
        opts = MarkdownReporterConfigOptions()
        assert opts.compact is False

    def test_compact_option_from_dict(self):
        """Config can be instantiated from a dict with compact=True."""
        config = MarkdownReporterConfig.model_validate(
            {"name": "markdown", "options": {"compact": True}}
        )
        assert config.options.compact is True
