# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""A release PR has to be able to trigger the checks that gate it.

Why this file exists
--------------------
A pull request opened with ``GITHUB_TOKEN`` does not start its workflows on its
own. GitHub used to create no runs for it at all: v3.5.0 through v3.5.3 arrived
with none of their required checks, and the branch ruleset waits for exactly
those, so the PR could not merge until a human pushed to it. Since June 2026
GitHub creates the runs in an approval-required state instead, and they start
only after a maintainer selects "Approve workflows to run". Every release PR
from v3.5.4 on was approved that way (each run shows ``run_attempt`` 2,
triggered by a maintainer, minutes after the PR opened). See
https://docs.github.com/en/actions/concepts/security/github_token.

An App-opened PR starts its checks with neither step.

Only the PR creation needs the App
----------------------------------
Both required checks trigger on ``pull_request``::

    ASH - Unified CI      on: pull_request: branches: ["**"]
    ASH - PR Title Check  on: pull_request: types: [opened, edited, synchronize]

so the event that has to fire is ``pull_request`` opened, and that is generated by
whoever *creates* the PR, not by whoever pushed the branch. ``gh pr create`` reads
``GH_TOKEN``; the push keeps the credential ``actions/checkout`` persists, which
stays the default ``GITHUB_TOKEN``.

An earlier revision handed the App token to checkout so the push would be
App-attributed too. That was wrong twice: it needs ``contents: write``, which is
not granted for Apps on these organizations, and with an App scoped to
``pull-requests: write`` the push would 403 without degrading -- the ``||``
fallback selects the App token whenever one exists, insufficient or not. So the
inverse is asserted below: checkout must *not* receive it.

Nothing is lost on the push side. The workflow already sets its git identity to
``github-actions[bot]``, so commit attribution is unchanged either way.

Why a fallback
--------------
The App credentials are repository secrets that have to be created by hand. Until
they exist, ``steps.app-token.outputs.token`` is empty, and a workflow that
insisted on it would fail to release at all. Without the App the cost is one
click by the maintainer who has to review and merge the PR anyway; failing
closed would turn that into no release until an App is approved and installed.
The fallback is kept, but it has to say so on the PR itself, because a warning
in the run log was not where the person who has to click was looking.
"""

from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "ash-create-release.yml"

TOKEN_ACTION = "actions/create-github-app-token"


@pytest.fixture(scope="module")
def workflow_text() -> str:
    return WORKFLOW.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def workflow(workflow_text):
    """Parsed workflow.

    Parsing matters on its own: GitHub rejects a malformed workflow by running
    zero jobs, with no annotation, which is a slow thing to notice.
    """
    return yaml.safe_load(workflow_text)


def _steps(workflow):
    jobs = workflow["jobs"]
    return jobs["create-release-pr"]["steps"]


def test_workflow_parses_and_has_the_release_job(workflow):
    assert "create-release-pr" in workflow["jobs"]
    assert _steps(workflow)


def test_an_app_token_is_minted(workflow_text):
    assert TOKEN_ACTION in workflow_text, (
        f"{TOKEN_ACTION} is not used, so the release PR is still created with "
        "GITHUB_TOKEN and will arrive with no checks."
    )


def test_the_token_action_is_pinned_to_a_major_version(workflow_text):
    """An unpinned action is a supply-chain risk in a release path."""
    assert f"{TOKEN_ACTION}@" in workflow_text, (
        f"{TOKEN_ACTION} is referenced without a version."
    )
    unpinned = f"{TOKEN_ACTION}@main"
    assert unpinned not in workflow_text, (
        "The token action is pinned to a moving branch in the workflow that cuts "
        "releases."
    )


def test_checkout_does_not_receive_the_app_token(workflow):
    """The push must stay on GITHUB_TOKEN, so the App needs no `contents: write`.

    Handing the App token to checkout makes `git push` authenticate as the App,
    which then requires `contents: write`. Two reasons not to:

    * Apps with direct write access to code are not granted on these
      organizations, so such a request would be refused.
    * With an App scoped to `pull-requests: write` the push would 403, and it
      would not degrade gracefully -- the `||` fallback selects the App token
      whenever one exists, insufficient or not. Releases would break the moment
      the App was installed.

    Only the PR creation needs the App identity, because both required checks
    trigger on `pull_request` and that event is generated by whoever creates the
    PR, not by whoever pushed the branch.
    """
    steps = _steps(workflow)
    checkout = next(s for s in steps if "actions/checkout" in str(s.get("uses", "")))

    token = str((checkout.get("with") or {}).get("token", ""))
    assert "app-token" not in token, (
        "actions/checkout is given the App token, so `git push` would "
        f"authenticate as the App and need `contents: write`: {token!r}"
    )


def test_the_pr_creation_step_prefers_the_app_token(workflow):
    steps = _steps(workflow)
    pr_steps = [s for s in steps if "gh pr create" in str(s.get("run", ""))]

    assert pr_steps, "No step runs `gh pr create`"
    for step in pr_steps:
        gh_token = str((step.get("env") or {}).get("GH_TOKEN", ""))
        assert "app-token" in gh_token, (
            f"`gh pr create` runs with {gh_token!r} rather than the App token, so "
            "the PR is attributed to GITHUB_TOKEN."
        )


def test_both_app_secrets_are_required_before_minting(workflow):
    """An id without a key must skip the App, not fail the release.

    create-github-app-token fails the step when the key is missing or malformed,
    and that step has no continue-on-error, so gating on the id alone would let a
    half-configured secret set kill the whole release job -- strictly worse than
    the degraded-but-working state this replaces. The `||` fallback cannot rescue
    it either: that only covers an absent output, never a failed step.
    """
    steps = _steps(workflow)
    detect = next(
        s for s in steps if "GITHUB_OUTPUT" in str(s.get("run", "")) and s.get("env")
    )

    env = detect.get("env") or {}
    referenced = " ".join(str(v) for v in env.values())

    assert "RELEASE_APP_CLIENT_ID" in referenced, (
        "The detect step does not read RELEASE_APP_CLIENT_ID."
    )
    assert "RELEASE_APP_PRIVATE_KEY" in referenced, (
        "The detect step never looks at RELEASE_APP_PRIVATE_KEY, so an id set "
        "without a key would still attempt the mint and fail the release job."
    )

    run = str(detect.get("run", ""))
    assert run.count("-n ") >= 2, (
        f"The detect step does not test both secrets for non-emptiness: {run!r}"
    )


def test_there_is_a_fallback_to_github_token(workflow_text):
    """Releases must still work before the App secrets exist.

    Asserted as a `||` fallback rather than by naming a step, so the expression
    stays readable if the step names change. Only GH_TOKEN needs it now that
    checkout is left on the default token.
    """
    assert "|| secrets.GITHUB_TOKEN" in workflow_text, (
        "There is no fallback to GITHUB_TOKEN. Until the App secrets are "
        "created, the release workflow would fail outright instead of falling "
        "back to today's behaviour."
    )


def _mint_step(workflow):
    steps = _steps(workflow)
    return next(s for s in steps if TOKEN_ACTION in str(s.get("uses", "")))


def test_the_mint_uses_client_id_not_the_deprecated_app_id(workflow):
    """v3 of the action deprecates `app-id` in favor of `client-id`."""
    inputs = _mint_step(workflow).get("with") or {}
    assert "app-id" not in inputs, (
        "create-github-app-token is given the deprecated `app-id` input."
    )
    assert "RELEASE_APP_CLIENT_ID" in str(inputs.get("client-id", "")), (
        "create-github-app-token is not given the client id secret."
    )


def test_the_app_token_is_scoped_to_what_pr_creation_needs(workflow):
    """Without `permission-*` inputs the token gets every installation permission.

    `gh pr create` needs Pull requests read and write, plus repository metadata,
    which every installation token carries without asking.
    """
    inputs = _mint_step(workflow).get("with") or {}
    granted = {k: v for k, v in inputs.items() if k.startswith("permission-")}
    assert granted == {
        "permission-pull-requests": "write",
    }, f"The App token permissions are not the minimal set: {granted!r}"


def test_the_app_token_requests_no_contents_permission(workflow):
    """The App is registered with no Contents permission at all, not even read.

    create-github-app-token fails the mint when it asks for a permission the
    installation does not hold, so a `permission-contents` input of any value
    would break every App-backed release. The push is GITHUB_TOKEN's job, and
    Apps with access to code are not granted on these organizations.
    """
    inputs = _mint_step(workflow).get("with") or {}
    assert "permission-contents" not in inputs, (
        "The App token requests a contents permission the App does not have: "
        f"{inputs.get('permission-contents')!r}"
    )


def test_the_fallback_says_so_on_the_pr(workflow):
    """A GITHUB_TOKEN release PR has to tell the maintainer to approve its runs.

    Until June 2026 the only signal was a warning in the run log, and that
    warning also described the old behavior (no runs, push to start them).
    """
    steps = _steps(workflow)
    pr_step = next(s for s in steps if "gh pr create" in str(s.get("run", "")))
    env = pr_step.get("env") or {}
    run = str(pr_step.get("run", ""))

    assert "steps.appcreds.outputs.present" in str(env.get("APP_TOKEN_USED", "")), (
        "The PR step cannot tell whether it is running on the App token."
    )
    assert "Approve workflows to run" in run, (
        "The fallback PR does not tell the maintainer to approve its workflow runs."
    )
    assert '--body "$BODY"' in run, (
        "The PR body is not the one that carries the approval note."
    )
    assert "GITHUB_STEP_SUMMARY" in run, (
        "The fallback is not reported in the run summary."
    )


def test_no_message_still_claims_a_push_is_needed(workflow_text):
    """The old warning said checks never start and a push was needed. Both are
    stale: GitHub now creates the runs, pending approval."""
    assert "will not trigger its required checks" not in workflow_text
    assert "push to the branch to start them" not in workflow_text
